properties:
  Id:
    type: string
    examples:
      - pgxbs-kftvjtgm
  IndividualId:
    type: string
    examples:
      - pgxind-kftx5ruq
  Description:
    type: string
    examples:
      - breast carcinoma
      - adenocarcinoma [cell line HeLa]
  Biocharacteristics:
    type: array
    elements: object
    $ref: "#/Characteristic"
    examples:
      - type:
          id: NCIT:C4029
          label: Cervical Adenocarcinoma
        type:
          id: UBERON:0000002
          label: uterine cervix
  ExternalReferences:
    type: array
    elements: object
    examples:
      - type:
          id: PMID:9892199
  IndividualAgeAtCollection:
    $ref: "#/Age"
  Provenance:
    $ref: "#/Provenance"
  DataUseConditions:
    $ref: "#/OntologyTerm"
  SampledTissue:
    $ref: "#/OntologyTerm"
  HistologicalDiagnosis:
    $ref: "#/OntologyTerm"
  Info:
    type: object
  Updated:
    type: string
    format: date-time
    examples:
      - "2020-09-10T17:44:10.170Z"
