"$schema": http://json-schema.org/draft-07/schema#
"$id": https://progenetix.org/schemas/Callset/v2020-12-08
properties:
  Id:
    type: string
    examples:
      - pgxcs-kftvldsu
  BiosampleId:
    type: string
    examples:
      - pgxbs-kftva59y
  Description:
    type: string
    examples:
      - SNP6 array
  ExternalReferences:
    type: array
    elements: object
    examples:
      - type:
          id: geo:GSM224836
  Provenance:
    $ref: "#/Provenance"
  DataUseConditions:
    $ref: "#/OntologyTerm"
  Info:
    type: object
  Updated:
    type: string
    format: date-time
    examples:
      - "2020-09-10T17:44:10.170Z"
