"$schema": http://json-schema.org/draft-07/schema#
"$id": https://progenetix.org/schemas/GeojsonPoint/v2020-12-08
properties:
  Type:
    type: string
    value: "Point"
  Coordinates:
    type: array
    values:
      type: number
      format: float
