properties:
  Label:
    type: string
    examples:
      - Heidelberg, Germany
      - Gainesville, United States of America
      - Zürich, Switzerland
  City:
    type: string
    examples:
      - Heidelberg
  Country:
    type: string
    examples:
      - Switzerland
  ISO-3166-alpha3:
    type: string
    examples:
      - USA
      - CHE
  Latitude:
    type: number
    format: float
    examples:
      - 47.37
  Longitude:
    type: number
    format: float
    examples:
      - 8.55
  Precision:
    type: string
    examples:
      - city
  Geojson:
    type: object
    schema: ./GeojsonPoint
