properties:
  Id:
    type: string
    examples:
      - pgxind-kftx25eh
  Description:
    type: string
    examples:
      - HapMap project contributor
  KaryotypicSex:
    $ref: "#/OntologyTerm"
  DateOfBirth:
    type: string
    format: date-time
  ExternalReferences:
    type: array
    elements: object
    examples:
      - type:
          id: NA19625
          label: HapMap individual
  Provenance:
    $ref: "#/Provenance"
  DataUseConditions:
    $ref: "#/OntologyTerm"
  Info:
    type: object
  Updated:
    type: string
    format: date-time
    examples:
      - "2020-09-10T17:44:10.170Z"
