defaults:
  dataset_ids:
    - progenetix
  response_type: biosample
  h->o_access_key: "biosamples._id"
  response_schema: beaconResultsetsResponse
  genome_binning: 1Mb
  test_document_id: pgxbs-kftvgkj3
bycon_definition_files:
  - beacon_info
  - beacon_endpoints
  - beacon_mappings
  - dataset_definitions
  - datatable_mappings
  - filter_definitions
  - geoloc_definitions
  - handover_definitions
  - interval_definitions
  - variant_definitions
meta: {}
response_types:
  - biosample
  - individual
  - genomicVariation
  - run
  - analysis
include_resultset_responses:
  - HIT
  - ALL
  - NONE
