defaults:
  dataset_ids:
    - progenetix
  response_type: biosample
  # response_schema: BeaconServiceResponse
  h->o_access_key: "biosamples._id"
  response_schema: beaconResultsetsResponse
  genome_binning: 1Mb
bycon_definition_files:
  - config
  - beacon_info
  - beacon_endpoints
  - beacon_mappings
  - dataset_definitions
  - datatable_mappings
  - filter_definitions
  - geoloc_definitions
  - handover_definitions
  - interval_definitions
  - variant_definitions
meta:
  returned_schemas:
    Biosample: https://progenetix.org/services/schemas/Biosample/
  info: >
    The main biosamples payload can be accessed in `resultSets`.
response_types:
  - biosample
  - individual
  - variantInSample
