selected_beacons:
  - cosmic
  - progenetix
  - bipmed
request_timeout: 30
beacon_params:
  cosmic:
    id: "COSMIC Beacon"
    base_url: https://cancer.sanger.ac.uk/api/ga4gh/beacon?format=json&
    api_version: 0.3
    parameter_map:
      include_dataset_responses:
        remap: includeDatasetResponses
        default: HIT
      assembly_id:
        remap: ref
        replace:
          - GRCh
          - ""
      alternate_bases:
        remap: allele
      start:
        remap: pos
        shift: 1
      reference_name:
        remap: chrom
      dataset_ids:
        remap: dataset
        default: cosmic
    response_map:
      response_summary:
        remap: response

  progenetix:
    id: "org.progenetix.beacon"
    base_url: http://progenetix.org/beacon/g_variants/?
    api_version: 2.0
    camelize: True
    parameter_map:
      assembly_id:
        remap: assemblyId
        default: GRCh38
    response_map: {}

  bipmed:
    id: "BIPMed"
    base_url: https://bcbcloud.fcm.unicamp.br/beacons/bipmed/query?
    api_version: 1.0
    camelize: True
    parameter_map:
      include_dataset_responses:
        remap: includeDatasetResponses
        default: HIT
      assembly_id:
        remap: assemblyId
        default: GRCh38
    response_map:
      response_summary:
        remap: response





# {
#   "query": {
#     "ref": "GRCh38",
#     "allele": "A",
#     "dataset": "cosmic",
#     "chrom": "7",
#     "pos": "140753336"
#   },
#   "version": "96",
#   "beacon_id": "COSMIC Beacon",
#   "response": {
#     "exists": "true"
#   }
# }