service_names:
  empty_value: info
  info: info
  filtering_terms: filteringTerms
  filteringTerms: filteringTerms
  datasets: datasets
  biosamples: biosamples
  individuals: individuals
  gVariants: variants
  g_variants: variants
  variants_in_sample: variants
  variantsInSample: variants
  variants: variants
