defaults:
  dataset_ids:
    - progenetix
  method: all
  response_type: biosample
  response_schema: BeaconServiceResponse
  h->o_access_key: "biosamples._id"
  genome_binning: 1Mb
bycon_definition_files:
  - config
  - beacon_info
  - beacon_endpoints
  - beacon_mappings
  - dataset_definitions
  - datatable_mappings
  - filter_definitions
  - geoloc_definitions
  - handover_definitions
  - interval_definitions
  - variant_definitions
meta:
  returned_schemas:
    Biosample: https://progenetix.org/services/schemas/Biosample/
  info: >
    The main biosamples payload can be accessed in `result_sets`.
response_types:
  - biosample
  - individual
  - variantInSample
methods:
  all:
    - _all_
  ids:
    - id
  details:
    - id
    - description
    - biocharacteristics
    - external_references
    - provenance
    - info
  biocharacteristics:
    - id
    - description
    - biocharacteristics
  callsetstats:
    - id
    - biosample_id
    - info.cnvstatistics
