defaults:
  response_type: return_biosamples
bycon_definition_files:
  - config
  - beacon_info
  - dataset_definitions
  - filter_definitions
  - geoloc_definitions
  - variant_definitions
  - handover_definitions
  - service_info
  - beacon_info
