defaults:
  dataset_ids:
    - progenetix
  method: details
  response_type: AnalysisResponse
  h->o_access_key: "callsets._id"
  genome_binning: 1Mb
bycon_definition_files:
  - config
  - beacon_info
  - beacon_mappings
  - dataset_definitions
  - filter_definitions
  - geoloc_definitions
  - handover_definitions
  - interval_definitions
  - variant_definitions
meta:
  returned_schemas:
    Analysis: https://progenetix.org/services/schemas/Callset/
  info: >
    The main individuals payload can be accessed in `response.results`.
response_types:
  - BiosampleResponse
  - AnalysisResponse
  - IndividualResponse
  - VariantInSampleResponse
methods:
  ids:
    - id
    - biosample_id
  details:
    - id
    - biosample_id
    - external_references
    - info
  pgxmatrix:
    - id
    - biosample_id
    - info
