bycon_definition_files:
  - config
  - beacon_mappings
  - dataset_definitions
  - filter_definitions
defaults:
  response_type: info
  response_schema: BeaconFilteringTermsResponse
  stats_number: 1
meta:
  api_version: 2.0.0-draft.4
  beacon_id: org.progenetix.beacon
  response_type: info
  returned_schemas:
    FilteringTerm: "https://progenetix.org/services/schemas/BeaconFilteringTermsResponse/"
  info: >
    The filtering terms can be accessed in `response`.
