bycon_definition_files:
  - config
  - beacon_mappings
  - dataset_definitions
  - filter_definitions
defaults:
  response_type: filtering_terms
  response_schema: beaconFilteringTermsResponse
  stats_number: 1
meta:
  api_version: v2.0.0-draft4
  beacon_id: org.progenetix.beacon
  response_type: filtering_terms
  returned_schemas:
    - entity_type: filtering_term
      schema: https://progenetix.org/services/schemas/beaconFilteringTermsResults#/definitions/FilteringTerm
  info: >
    The filtering terms can be accessed in `response`.
