bycon_definition_files:
  - config
  - beacon_mappings
  - dataset_definitions
  - filter_definitions
defaults:
  method: ""
  response_type: info
  stats_number: 1
meta:
  beacon_id: org.progenetix
  response_type: info
  returned_schemas:
    FilteringTerm: "https://progenetix.org/services/schemas/BeaconFilteringTermsResponse/"
  info: >
    The filtering terms can be accessed in `response`.
methods:
  counts:
    - counts
  filtering_terms:
    - counts
    - filtering_terms
