defaults:
  dataset_ids:
    - progenetix
  method: details
  response_type: IndividualResponse
  h->o_access_key: "individuals._id"
bycon_definition_files:
  - config
  - beacon_info
  - beacon_mappings
  - dataset_definitions
  - filter_definitions
  - geoloc_definitions
  - variant_definitions
  - handover_definitions
meta:
  returned_schemas:
    Individual: https://progenetix.org/services/schemas/Individual/
  info: >
    The main individuals payload can be accessed in `response.results`.
response_types:
  - BiosampleResponse
  - IndividualResponse
  - VariantInSampleResponse
methods:
  ids:
    - id
  details:
    - id
    - description
    - biocharacteristics
    - external_references
    - provenance
    - info
  biocharacteristics:
    - id
    - description
    - biocharacteristics
