defaults:
  dataset_ids:
    - progenetix
  method: details
  response_type: individual
  h->o_access_key: "individuals._id"
  genome_binning: 1Mb
bycon_definition_files:
  - config
  - beacon_info
  - beacon_mappings
  - dataset_definitions
  - datatable_mappings
  - filter_definitions
  - geoloc_definitions
  - interval_definitions
  - handover_definitions
  - variant_definitions
meta:
  returned_schemas:
    Individual: https://progenetix.org/services/schemas/Individual/
  info: >
    The main individuals payload can be accessed in `response.result_sets`.
response_types:
  - biosample
  - individual
  - variantInSample
methods:
  ids:
    - id
  details:
    - id
    - description
    - biocharacteristics
    - external_references
    - provenance
    - info
  biocharacteristics:
    - id
    - description
    - biocharacteristics
