bycon_definition_files:
  - config
  - dataset_definitions
  - beacon_info
  - beacon_mappings
defaults:
  method: ""
  response_type: return_beacon_info
  stats_number: 1
meta:
  beacon_id: org.progenetix
  response_type: info
  returned_schemas:
    BeaconInfo: "https://beacon-project.io/schemas/beacon-v2/current/BeaconInfo.json"
  info: >
    The latest BeaconInfo payload can be accessed in `response.result_sets`.
methods: {}
