bycon_definition_files:
  - config
  - dataset_definitions
  - beacon_info
  - beacon_mappings
defaults:
  response_type: info
  stats_number: 1
meta:
  beacon_id: org.progenetix
  response_type: info
  returned_schemas:
    - entity_type: info
      schema: https://progenetix.org/services/schemas/beaconInfoResponse
  info: >-
    The latest BeaconInfo payload can be accessed in `response`.
