defaults:
  dataset_ids:
    - progenetix
  response_type: map
  genome_binning: 1Mb
bycon_definition_files:
  - config
  - beacon_info
  - beacon_endpoints
  - beacon_mappings
  - dataset_definitions
  - filter_definitions
  - geoloc_definitions
  - handover_definitions
  - interval_definitions
  - variant_definitions
meta:
  returned_schemas:
    - entity_type: map
      schema: https://progenetix.org/services/schemas/beaconMapResponse/
  info: >-
    Beacon map.
response_types:
  - map
response:
  $schema: https://progenetix.org/services/schemas/beaconMapResponse/
  endpoint_sets:
    dataset:
      entry_type: dataset
      openAPIEndpointsDefinition: https://progenetix.org/services/endpoints/datasets/
      root_url: https://progenetix.org/beacon/datasets
      single_entry_url: https://progenetix.org/beacon/datasets/{id}
      filtering_terms_url: https://progenetix.org/beacon/filteringTerms/?datasetIds={id}
    cohort:
      entry_type: cohort
      openAPIEndpointsDefinition: https://progenetix.org/services/endpoints/cohorts/
      root_url: https://progenetix.org/beacon/cohorts
      single_entry_url: https://progenetix.org/beacon/cohorts/{id}
      filtering_terms_url: https://progenetix.org/beacon/filteringTerms/
    biosample:
      entry_type: biosample
      openAPIEndpointsDefinition: https://progenetix.org/services/endpoints/biosamples/
      root_url: https://progenetix.org/beacon/biosamples
      single_entry_url: https://progenetix.org/beacon/biosamples/{id}
      filtering_terms_url: https://progenetix.org/beacon/biosamples/filteringTerms
      endpoints:
        genomic_variation:
          returned_entry_type: variant
          url: https://progenetix.org/beacon/biosamples/{id}/variants
        biosample:
          returned_entry_type: biosample
          url: https://progenetix.org/beacon/biosamples/{id}/biosamples
        individual:
          returned_entry_type: individual
          url: https://progenetix.org/beacon/biosamples/{id}/individuals
        analysis:
          returned_entry_type: analysis
          url: https://progenetix.org/beacon/biosamples/{id}/analyses
        run:
          returned_entry_type: run
          url: https://progenetix.org/beacon/biosamples/{id}/runs
    analysis:
      entry_type: analysis
      openAPIEndpointsDefinition: https://progenetix.org/services/endpoints/analyses/
      root_url: https://progenetix.org/beacon/analyses
      single_entry_url: https://progenetix.org/beacon/analyses/{id}
      filtering_terms_url: https://progenetix.org/beacon/filteringTerms
      endpoints:
        genomic_variation:
          returned_entry_type: variant
          url: https://progenetix.org/beacon/analyses/{id}/variants
        biosample:
          returned_entry_type: biosample
          url: https://progenetix.org/beacon/analyses/{id}/biosamples
        individual:
          returned_entry_type: individual
          url: https://progenetix.org/beacon/analyses/{id}/individuals
        run:
          returned_entry_type: run
          url: https://progenetix.org/beacon/analyses/{id}/runs
    run:
      entry_type: run
      openAPIEndpointsDefinition: https://progenetix.org/services/endpoints/runs/
      root_url: https://progenetix.org/beacon/runs
      single_entry_url: https://progenetix.org/beacon/runs/{id}
      filtering_terms_url: https://progenetix.org/beacon/runs/filteringTerms
      endpoints:
        genomic_variation:
          returned_entry_type: genomic_variation
          url: https://progenetix.org/beacon/runs/{id}/genomicVariations
        biosample:
          returned_entry_type: biosample
          url: https://progenetix.org/beacon/runs/{id}/biosamples
        individual:
          returned_entry_type: individual
          url: https://progenetix.org/beacon/runs/{id}/individuals
    individual:
      openAPIEndpointsDefinition: https://progenetix.org/services/endpoints/individuals/
      entry_type: individual
      root_url: https://progenetix.org/beacon/individuals
      single_entry_url: https://progenetix.org/beacon/individuals/{id}
      filtering_terms_url: https://progenetix.org/beacon/individuals/filteringTerms
      endpoints:
        genomic_variation:
          returned_entry_type: genomicVariation
          url: https://progenetix.org/beacon/individuals/{id}/genomicVariations
        biosample:
          returned_entry_type: biosample
          url: https://progenetix.org/beacon/individuals/{id}/biosamples
        individual:
          returned_entry_type: individual
          url: https://progenetix.org/beacon/individuals/{id}/individuals
    genomic_variation:
      openAPIEndpointsDefinition: https://progenetix.org/services/endpoints/variants/
      filtering_terms_url: https://progenetix.org/beacon/variants/filteringTerms
      entry_type: variant
      root_url: https://progenetix.org/beacon/variants
      single_entry_url: https://progenetix.org/beacon/variants/{id}
      filtering_terms_url: https://progenetix.org/beacon/filteringTerms/
