defaults:
  dataset_ids:
    - progenetix
  response_type: variantInterpretation
  response_schema: BeaconServiceResponse
  collection_name: variant_annotations
meta:
  returned_schemas:
    Variant: https://progenetix.org/services/schemas/Variant/
  info: >
    The main variants interpretations payload can be accessed in `resultSets`.
bycon_definition_files:
  - config
  - beacon_info
  - beacon_mappings
  - dataset_definitions
  - filter_definitions
  - handover_definitions
  - interval_definitions
  - variant_definitions
all_variants_methods:
  - callsetsvariants
  - callsetspgxseg
response_types:
  - variantInterpretation
  - individual
  - biosample
