defaults:
  dataset_ids:
    - progenetix
  method: details
  response_type: variantInSample
  response_schema: BeaconServiceResponse
  genome_binning: 1Mb
meta:
  returned_schemas:
    Variant: https://progenetix.org/services/schemas/Variant/
  info: >
    The main variants payload can be accessed in `result_sets`.
bycon_definition_files:
  - config
  - beacon_info
  - beacon_mappings
  - dataset_definitions
  - datatable_mappings
  - filter_definitions
  - geoloc_definitions
  - handover_definitions
  - interval_definitions
  - variant_definitions
all_variants_methods:
  - callsetsvariants
  - callsetspgxseg
response_types:
  - variantInSample
  - variantInterpretation
  - individual
  - biosample
methods:
  digests:
    - digest
  compact:
    - _id
    - biosample_id
    - reference_name
    - start
    - end
    - variant_type
    - reference_bases
    - alternate_bases
  details:
    - _id
    - biosample_id
    - callset_id
    - digest
    - reference_name
    - start
    - end
    - variant_type
    - reference_bases
    - alternate_bases
    - info
