bycon_definition_files:
  - config
  - beacon_info
  - beacon_mappings
  - dataset_definitions
  - filter_definitions
defaults:
  response_type: return_dbstats
  response_schema: beaconCollectionsResponse
  stats_number: 1
  include_resultset_responses: HIT
  test_document_id: progenetix
meta:
  beacon_id: org.progenetix
  response_type: info
  returned_schemas:
    - entity_type: dataset
      schema: https://progenetix.org/services/schemas/dataset/
  received_request_summary:
    requested_granularity: record
    include_resultset_responses: HIT
    requested_schemas:
      - https://progenetix.org/services/schemas/dataset/
  returned_granularity: record
  info: >
    The latest dbstats payload can be accessed in `results`.
include_resultset_responses:
  - HIT
  - ALL
  - NONE
