bycon_definition_files:
  - config
  - beacon_mappings
  - dataset_definitions
  - filter_definitions
defaults:
  response_type: return_dbstats
  response_schema: BeaconServiceResponse
  stats_number: 1
meta:
  beacon_id: org.progenetix
  response_type: info
  returned_schemas:
    BeaconDataset: "https://progenetix.org/services/schemas/BeaconDataset/"
  info: >
    The latest dbstats payload can be accessed in `results`.
