bycon_definition_files:
  - config
  - beacon_info
  - beacon_mappings
  - dataset_definitions
  - filter_definitions
  - variant_definitions
  - interval_definitions
  - handover_definitions
defaults:
  response_type: dataset
  stats_number: 1
  test_document_id: progenetix
meta:
  beacon_id: org.progenetix
  returned_schemas:
    - entity_type: dataset
      schema: https://progenetix.org/services/schemas/dataset
  received_request_summary:
    requested_granularity: record
    requested_schemas:
      - entity_type: dataset
        schema: https://progenetix.org/services/schemas/dataset
  returned_granularity: record
include_resultset_responses:
  - HIT
  - ALL
  - NONE
response_types:
  - biosample
  - individual
  - genomicVariation
  - run
  - analysis
  - dataset
  - info

