"$schema": https://json-schema.org/draft/2020-12/schema
"$id": https://progenetix.org/services/schemas/ServiceResponseResults/v2020-12-18
title: ServiceResponseResults
description: >
  The results of the service request.
properties:
  exists:
    type: boolean
  info:
    type: object
  results:
    type: array
