"$schema": https://json-schema.org/draft/2020-12/schema
"$id": https://progenetix.org/services/schemas/ServiceResponseMeta/v2020-12-18
title: ServiceResponseMeta
description: >
  The metadata (e.g. query, environment) of the service request and response.
properties:
  responseType:
    type: string
  errors:
    type: array
    items:
      type: string
  parameters:
    type: array
    items:
      type: object
  returnedSchemas:
    type: array
    items:
      type: string
  info:
    type: object
