"$schema": https://json-schema.org/draft/2020-12/schema
"$id": https://progenetix.org/services/schemas/ServiceResponseResults/v2020-12-18
title: ServiceResponseResults
description: >
  The results of the service request.
properties:
  error:
    type: object
  exists:
    type: boolean
  info:
    type: object
  results:
    type: array
    items:
      type: object
  beaconHandover:
    type: array
    items:
      type: object
  resultsHandover:
    type: array
    items:
      type: object
