---
bycon_definition_files:
  - config
  - filter_definitions
  - dataset_definitions
dataset_ids:
  # - arraymap
  - progenetix
refreshing:
  cnvstatistics:
    cnvcoverage: []
    delfraction: []
    cnvfraction: []
    delcoverage: []
    dupfraction: []
    dupcoverage: []
