---
bycon_definition_files:
  - config
  - filter_definitions
  - dataset_definitions
  - interval_definitions
  - handover_definitions
  - variant_definitions
defaults:
    genome_binning: 1Mb
dataset_ids:
  - progenetix
  - cellosaurus
  - 1000genomesDRAGEN
refreshing:
  cnvstatistics:
    cnvcoverage: []
    delfraction: []
    cnvfraction: []
    delcoverage: []
    dupfraction: []
    dupcoverage: []
pathologicalTnmFindings:
  T3:
    id: "NCIT:C48728"
    label: "T3 Stage Finding"
    pattern: "^.*?T3[^abcd]*?$"
  T3d:
    id: "NCIT:C148412"
    label: "T3d Stage Finding"
    pattern: "^.*?T3d.*?$"
  N2:
    id: "NCIT:C48786"
    label: "N2 Stage Finding"
    pattern: "^.*?N2[^abcd]*?$"
