---
dataset_ids:
  - arraymap
  - progenetix
data_collections:
  - biosamples
ontologymaps:
  ICD2UBERON:
    prefixes:
      - icdot
      - UBERON
  ICDOntologies:
    prefixes:
      - NCIT
      - icdom
      - icdot
    mappingfile:
      - rsrc
      - ICDOntologies.ods
