bycon_definition_files:
  - beacon_info
  - beacon_mappings
  - cohort_definitions
  - dataset_definitions
  - filter_definitions
defaults:
  response_type: cohort
  stats_number: 1
  test_document_id: TCGAcancers
  pagination:
    skip: 0
    limit: 2000
  include_resultset_responses: true
meta:
  beacon_id: org.progenetix
  returned_schemas:
    - entity_type: cohort
      schema: https://progenetix.org/services/schemas/cohort
  received_request_summary:
    requested_granularity: record
    requested_schemas:
      - entity_type: cohort
        schema: https://progenetix.org/services/schemas/cohort
  returned_granularity: record
