bycon_definition_files:
  - config
  - beacon_info
  - beacon_mappings
  - cohort_definitions
  - dataset_definitions
  - filter_definitions
defaults:
  response_type: cohort
  stats_number: 1
  test_document_id: TCGAcancers
meta:
  beacon_id: org.progenetix
  returned_schemas:
    - entity_type: cohort
      schema: https://progenetix.org/services/schemas/cohort
  received_request_summary:
    requested_granularity: record
    requested_schemas:
      - entity_type: cohort
        schema: https://progenetix.org/services/schemas/cohort
  returned_granularity: record
include_resultset_responses:
  - HIT
  - ALL
  - NONE
