bycon_definition_files:
  - beacon_info
  - beacon_mappings
  - dataset_definitions
  - datatable_mappings
  - filter_definitions
  - geoloc_definitions
  - handover_definitions
  - interval_definitions
  - variant_definitions
defaults:
  dataset_ids:
    - progenetix
  response_type: individual
  response_schema: beaconResultsetsResponse
  genome_binning: 1Mb
  test_document_id: pgxind-kftx25eh
  pagination:
    skip: 0
    limit: 2000
  include_resultset_responses: true
meta:
  returned_schemas:
    - entity_type: individual
      schema: https://progenetix.org/services/schemas/individual
  received_request_summary:
    requested_granularity: record
    include_resultset_responses: HIT
    requested_schemas:
      - entity_type: individual
        schema: https://progenetix.org/services/schemas/individual
  returned_granularity: record
  info: >
    The main payload can be accessed in `response.resultSets`.
response_types:
  - phenopacket
  - biosample
  - individual
  - variant
  - run
  - analysis
