defaults:
  dataset_ids:
    - progenetix
  response_type: individual
  response_schema: beaconResultsetsResponse
  h->o_access_key: "individuals._id"
  genome_binning: 1Mb
  test_document_id: pgxbs-kftvgkj3
bycon_definition_files:
  - config
  - beacon_info
  - beacon_mappings
  - dataset_definitions
  - datatable_mappings
  - filter_definitions
  - geoloc_definitions
  - interval_definitions
  - handover_definitions
  - variant_definitions
meta:
  returned_schemas:
    - entity_type: dataset
      schema: https://progenetix.org/services/schemas/Individual/
  received_request_summary:
    requested_granularity: record
    include_resultset_responses: HIT
    requested_schemas:
      - https://progenetix.org/services/schemas/Individual/
  returned_granularity: record
  info: >
    The main payload can be accessed in `response.resultSets`.
response_types:
  - biosample
  - individual
  - variantInSample
include_resultset_responses:
  - HIT
  - ALL
  - NONE
