defaults:
  dataset_ids:
    - progenetix
  response_type: analysis
  response_schema: beaconResultsetsResponse
  h->o_access_key: "callsets._id"
  genome_binning: 1Mb
  test_document_id: pgxcs-kftvmpc0
bycon_definition_files:
  - config
  - beacon_info
  - beacon_mappings
  - dataset_definitions
  - datatable_mappings
  - filter_definitions
  - geoloc_definitions
  - handover_definitions
  - interval_definitions
  - variant_definitions
meta:
  returned_schemas:
    - entity_type: analysis
      schema: https://progenetix.org/services/schemas/analysis/
  received_request_summary:
    requested_granularity: record
    include_resultset_responses: HIT
    requested_schemas:
      - entity_type: analysis
        schema: https://progenetix.org/services/schemas/analysis/
  returned_granularity: record
  info: >-
    The main individuals payload can be accessed in `results`.
response_types:
  - biosample
  - analysis
  - individual
  - genomicVariation
include_resultset_responses:
  - HIT
  - ALL
  - NONE
