defaults:
  dataset_ids:
    - progenetix
  genome_binning: 1Mb
  response_schema: beaconResultsetsResponse
  include_resultset_responses: HIT
  include_handovers: false
  requested_granularity: record
  returned_granularity: record
  pagination:
    skip: 0
    limit: 2000
  response_entity:
    entity_type: dataset
    collection: dbstats
    response_schema: progenetixServiceResponse
    beacon_schema:
      entity_type: dataset
      schema: https://progenetix.org/services/schemas/dataset/
    h->o_access_key: False

bycon_definition_files:
  - beacon_defaults
  - beacon_mappings
  - dataset_definitions
  - datatable_mappings
  - filter_definitions
  - geoloc_definitions
  - handover_definitions
  - interval_definitions
  - remap_definitions
  - service_mappings
  - variant_definitions

info:
  beacon_id: org.progenetix.beacon
  name: Progenetix Cancer Genomics Beacon+
  api_version: v2.0.0
  version: v2.0.0
  id: org.progenetix.beacon
  environment: prod
  description: >-
    Beacon+ provides a forward looking implementation of the Beacon v2 API, with
    focus on structural genome variants and metadata based on the cancer and reference
    genome profiling data in the Progenetix oncogenomic data resource (https://progenetix.org).
  type:
    group: org.ga4gh
    artifact: Beacon v2
    version: v2.0.0
  documentation_url: http://docs.progenetix.org
  service_url: http://progenetix.org/beacon/
  welcome_url: https://progenetix.org/biosamples/
  alternative_url: https://progenetix.org
  contact_url: mailto:contact@progenetix.org
  created_at: 2015-11-13T00:00:00
  updated_at: 2022-04-12T08:45:00
  organization:
    id: org.baudisgroup.info
    name: Theoretical Cytogenetics and Oncogenomics group at UZH and SIB
    description: >
      The *Theoretical Cytogenetics and Oncogenomics* group at the University of
      Zurich (UZH) and the Swiss Institute of Bioinformatics (SIB) performs research
      in cancer genomics and provides bioinformatics tools and cancer genome data
      resources to the scientific community.
    address: >-
      Department of Molecular Life Sciences
      University of Zurich
      Winterthurerstrasse 190
      CH-8057 Zurich
      Switzerland
    welcome_url: https://progenetix.org/biosamples/
    contact_url: mailto:contact@progenetix.org
    logoUrl: https://progenetix.org/p/progenetix.png
    info:
      update_date_time: 2022-04-12T08:45:00
  create_date_time: 2015-11-13T00:00:00
  update_date_time: 2022-04-12T08:45:00

map:
  response_type: beaconMap
  response_schema: beaconMapResponse

entry_types:
  response_type: entryType
  response_schema: beaconEntryTypesResponse

filtering_terms:
  response_type: filteringTerm
  response_schema: beaconFilteringTermsResponse

analyses:
  response_type: analysis
  h->o_access_key: "callsets._id"

biosamples:
  response_type: biosample
  h->o_access_key: "biosamples._id"

cohorts:
  response_type: cohort
  response_schema: beaconCollectionsResponse
  pagination:
    skip: 0
    limit: 10
  include_resultset_responses: false

datasets:
  response_type: dataset
  response_schema: beaconCollectionsResponse
  pagination:
    skip: 0
    limit: 5
  include_resultset_responses: false

individuals:
  response_type: individual
  h->o_access_key: "individuals._id"

runs:
  response_type: run
  h->o_access_key: "callsets._id"

genomicVariations:
  response_type: genomicVariant
  h->o_access_key: "variants._id"

