---
beacon_id: 'org.progenetix.beacon'
name: 'Progenetix Cancer Genomics Beacon+'
api_version: v2.0.0
id: org.baudisgroup.info
environment: dev
organization:
  id: "org.baudisgroup.info"
  name: "baudisgroup at UZH and SIB"
  description: >
    The "Theoretical Cytogenetics and Oncogenomics" group at the University of Zurich (UZH) and the Swiss Institute of Bioinformatics (SIB) performs research in cancer genomics and provides bioinformatics tools and cancer genome data resources to the scientific community.
  address: "Department of Molecular Life Sciences, University of Zurich, Winterthurerstrasse 190, CH-8057"
  welcomeUrl: "https://info.baudisgroup.org"
  contactUrl: "mailto:contact@progenetix.org"
  logoUrl: "https://progenetix.org/p/progenetix.png"
  info:
    updateDateTime: 2022-02-22
description: >-
  Beacon+ provides a forward looking implementation of the Beacon API, with focus on structural variants and metadata based on the cancer and reference genome profiling data represented in the Progenetix oncogenomic data resource (https://progenetix.org).
version: v2
welcomeUrl: "https://progenetix.org/beaconplus-instances/beaconplus/"
alternativeUrl: "https://progenetix.org"
create_date_time: "2015-11-13T00:00:00"
update_date_time: "2021-07-21T00:00:00"
datasets: [ ] # populated from script
