id_queryscope_mappings:
  biosampleIds: biosamples
  variantIds: variants
  callsetIds: callsets
  analysisIds: callsets
  individualIds: individuals

service_aliases:
  empty_value: info
  info: info
  service_info: service_info
  "service-info": service_info
  analyses: analyses
  callsets: analyses
  cohorts: cohorts
  configuration: configuration
  entryTypes: entryTypes
  entry_types: entryTypes
  filtering_terms: filteringTerms
  filteringTerms: filteringTerms
  collections: datasets
  datasets: datasets
  biosamples: biosamples
  individuals: individuals
  map: map
  runs: runs
  gVariants: g_variants
  g_variants: g_variants
  genomicVariations: g_variants
  variants: g_variants

data_pipeline_entry_types:
  - analyses
  - biosamples
  - individuals
  - g_variants
  - runs

#response_type_aliases:
default_schema_from_model:
  biosample: biosamples
  variant: genomicVariations
  g_variant: genomicVariations
  genomicVariant: genomicVariations
  individual: individuals
  dataset: datasets
  cohort: cohorts
  run: runs
  analysis: analyses
  callset: analyses
  phenopacket: phenopackets

path_response_type_mappings:

  analyses: analysis
  callsets: analysis
  cohorts: cohort
  collections: dataset
  datasets: dataset
  biosamples: biosample
  individuals: individual
  runs: run
  gVariants: genomicVariant
  g_variants: genomicVariant
  map: beaconMap
  variants: genomicVariant
  variants_in_sample: genomicVariant
  variantsInSample: genomicVariant
  variantInterpretations: genomicVariant
  variant_interpretations: genomicVariant
  info: info
  filtering_terms: filteringTerm

response_types:

  - entity_type: info
    collection: Null
    response_schema: beaconInfoResponse
    beacon_schema:
      entity_type: configuration
      schema: https://progenetix.org/services/schemas/beaconInfoResults/
    h->o_access_key: Null

  - entity_type: configuration
    collection: Null
    response_schema: beaconConfigurationResponse
    beacon_schema:
      entity_type: configuration
      schema: https://progenetix.org/services/schemas/beaconConfigurationSchema/
    h->o_access_key: Null

  - entity_type: entryTypes
    collection: Null
    response_schema: beaconEntryTypesResponse
    beacon_schema:
      entity_type: entryType
      schema: https://progenetix.org/services/schemas/entryTypesSchema/
    h->o_access_key: Null

  - entity_type: map
    collection: Null
    response_schema: beaconMapResponse
    beacon_schema:
      entity_type: map
      schema: https://progenetix.org/services/schemas/beaconMapSchema/
    h->o_access_key: Null

  - entity_type: filteringTerm
    collection: Null
    response_schema: beaconFilteringTermsResponse
    beacon_schema:
      entity_type: filteringTerm
      schema: https://progenetix.org/services/schemas/filteringTermsSchema/
    h->o_access_key: Null

  - entity_type: dataset
    collection: dbstats
    response_schema: beaconCollectionsResponse
    beacon_schema:
      entity_type: dataset
      schema: https://progenetix.org/services/schemas/dataset/
    h->o_access_key: Null

  - entity_type: cohort
    collection: collations
    response_schema: beaconCollectionsResponse
    beacon_schema:
      entity_type: cohort
      schema: https://progenetix.org/services/schemas/cohort/
    h->o_access_key: Null

  - entity_type: individual
    collection: individuals
    response_schema: beaconResultsetsResponse
    beacon_schema:
      entity_type: individual
      schema: https://progenetix.org/services/schemas/individual/
    h->o_access_key: "individuals._id" 

  - entity_type: phenopacket
    collection: individuals
    response_schema: beaconResultsetsResponse
    beacon_schema:
      entity_type: phenopacket
      schema: https://progenetix.org/services/schemas/phenopacket/
    h->o_access_key: "individuals._id"

  - entity_type: biosample
    collection: biosamples
    response_schema: beaconResultsetsResponse
    beacon_schema:
      entity_type: biosample
      schema: https://progenetix.org/services/schemas/biosample/
    h->o_access_key: "biosamples._id"

  - entity_type: analysis
    collection: callsets  
    response_schema: beaconResultsetsResponse
    beacon_schema:
      entity_type: analysis
      schema: https://progenetix.org/services/schemas/analysis/
    h->o_access_key: "callsets._id"

  - entity_type: run
    collection: callsets
    response_schema: beaconResultsetsResponse
    beacon_schema:
      entity_type: run
      schema: https://progenetix.org/services/schemas/run/
    h->o_access_key: "callsets._id"

  - entity_type: genomicVariant
    response_schema: beaconResultsetsResponse
    collection: variants
    beacon_schema:
      entity_type: genomicVariant
      schema: https://progenetix.org/services/schemas/genomicVariant/    
    h->o_access_key: "variants._id"

