$schema: https://raw.githubusercontent.com/ga4gh-beacon/beacon-framework-v2/main/configuration/beaconMapSchema.json
endpointSets:
  dataset:
    entryType: dataset
    openAPIEndpointsDefinition: "./datasets/endpoints.yaml"
    rootUrl: https://progenetix.org/beacon/datasets
    singleEntryUrl: https://progenetix.org/beacon/datasets/{id}
    filteringTermsUrl: https://progenetix.org/beacon/filteringTerms/?datasetIds={id}
    endpoints: https://progenetix.org/beacon/datasets
  biosample:
    entryType: biosample
    openAPIEndpointsDefinition: "./biosamples/endpoints.yaml"
    rootUrl: https://progenetix.org/beacon/biosamples
    singleEntryUrl: https://progenetix.org/beacon/biosamples/{id}
    filteringTermsUrl: https://progenetix.org/beacon/filteringTerms
    endpoints:
      variantInSample:
        returnedEntryType: variantInSample
        url: https://progenetix.org/beacon/biosamples/{id}/variantsInSample
      biosample:
        returnedEntryType: biosample
        url: https://progenetix.org/beacon/biosamples/{id}/biosample
      individual:
        returnedEntryType: biosample
        url: https://progenetix.org/beacon/biosamples/{id}/individual
  variantInSample:
    entryType: genomicVariant
    openAPIEndpointsDefinition: "./variantsInSample/endpoints.yaml"
    rootUrl: https://progenetix.org/beacon/variantsInSample
    singleEntryUrl: https://progenetix.org/beacon/variantsInSample/{id}
    filteringTermsUrl: https://progenetix.org/beacon/filteringTerms/?datasetIds={dataset_id}
