service_names:
  empty_value: info
  info: info
  filtering_terms: filteringTerms
  filteringTerms: filteringTerms
  datasets: datasets
  biosamples: biosamples
  individuals: individuals
  gVariants: variants
  g_variants: variants
  variants_in_sample: variants
  variantsInSample: variants
  variants: variants
  variantsInterpretations: variantsInterpretations
  variants_interpretations: variantsInterpretations
  analyses: callsets
  callsets: callsets

response_types:
  biosamples:
    id: biosample
    schema: https://progenetix.org/services/schemas/Biosample/
    h->o_access_key: "biosamples._id"
  individuals:
    id: individual
    schema: https://progenetix.org/services/schemas/Individual/
    h->o_access_key: "individuals._id"
  variants:
    id: variantInSample
    schema: https://progenetix.org/services/schemas/Variant/
    h->o_access_key: "variants._id"
  g_variants:
    id: variantInSample
    schema: https://progenetix.org/services/schemas/Variant/
    h->o_access_key: "variants._id"
  variants_in_sample:
    id: variantInSample
    schema: https://progenetix.org/services/schemas/Variant/
    h->o_access_key: "variants._id"
  variants_interpretations:
    id: variantInterpretation
    schema: https://progenetix.org/services/schemas/Variant/
    h->o_access_key: "variant_annotations._id"
  callsets:
    id: analysis
    schema: https://progenetix.org/services/schemas/Callset/
    h->o_access_key: "callsets._id"
  analyses:
    id: analysis
    schema: https://progenetix.org/services/schemas/Callset/
    h->o_access_key: "callsets._id"


