GEOseries:
  prefix: geo
  type: Gene Expression Omnibus series
  pattern: '^(geo)[:]GSE\d+?$'
  scope: biosamples
  db_key: 'external_references.id'
  is_series: True
  child_pattern: '^(geo)[:]GSM'

GEOplatform:
  prefix: geo
  type: Gene Expression Omnibus platform
  pattern: '^(geo)[:]GPL\d+?$'
  scope: biosamples
  db_key: 'external_references.id'
  is_series: True
  child_pattern: '^(geo)[:]GSM'

NCIT:
  prefix: NCIT
  type: National Cancer Institute Thesaurus Neoplasia Code
  pattern: '^(NCIT)[:]C'
  scope: biosamples
  db_key: 'histological_diagnosis.id'
  is_series: False

NCITgrade:
  prefix: NCIT
  type: National Cancer Institute Thesaurus Disease Grade Qualifier
  pattern: '^(NCIT)[\:]C'
  scope: biosamples
  db_key: 'tumor_grade.id'
  is_series: False

NCITstage:
  prefix: NCIT
  type: National Cancer Institute Thesaurus Disease Stage Qualifier
  pattern: '^(NCIT)[\:]C'
  scope: biosamples
  db_key: 'pathological_stage.id'
  is_series: False

EFOfus:
  prefix: EFO
  type: EFO followup status classes
  pattern: '^(EFO)[\:]\d'
  scope: biosamples
  db_key: 'followup_state.id'
  is_series: False

PATOsex:
  prefix: PATO
  type: Phenotypic Qualities Ontology codes for genotypic sex
  pattern: '^(PATO)[\:]\d'
  scope: individuals
  db_key: 'sex.id'
  is_series: False

EFO:
  prefix: EFO
  type: Experimental Factor Ontology Biosample Status
  pattern: '^((?:EFO)|(?:OBI))[\:]\d+?$'
  scope: biosamples
  db_key: 'biosample_status.id'
  is_series: False

NCITtnm:
  prefix: NCIT
  type: National Cancer Institute Thesaurus Cancer TNM Finding
  pattern: '^(NCIT)[\:]C'
  scope: biosamples
  db_key: 'pathological_tnm_findings.id'
  is_series: False

icdom:
  prefix: icdom
  type: ICD-O 3 Morphologies (Progenetix)
  pattern: '^(icdom)[\-]\d'
  scope: biosamples
  db_key: 'icdo_morphology.id'
  is_series: False

icdot:
  prefix: icdot
  type: ICD-O 3 Topographies (Progenetix)
  pattern: '^(icdot)[\-]C'
  scope: biosamples
  db_key: 'icdo_topography.id'
  is_series: False

cellosaurus:
  prefix: cellosaurus
  type: Cellosaurus cell line identifiers
  pattern: '^(cellosaurus)[:]CVCL'
  scope: biosamples
  db_key: 'external_references.id'
  is_series: False

PMID:
  prefix: PMID
  type: PubMed publication identifier
  pattern: '^(PMID)[:]\d'
  scope: biosamples
  db_key: 'external_references.id'
  is_series: False

UBERON:
  prefix: UBERON
  type: Uberon cross-species anatomical structures ontology
  pattern: '^(UBERON)[:]\d'
  scope: biosamples
  db_key: 'sampled_tissue.id'
  is_series: False

cBP:
  prefix: cBP
  type: cBioPortal Study
  pattern: '^(cBP)[\-]\w'
  scope: biosamples
  db_key: 'external_references.id'
  is_series: False

TCGAproject:
  prefix: TCGA
  type: The Cancer Genome Atlas Project
  pattern: '^(TCGA)[\-][\w\-]{2,6}$'
  scope: biosamples
  db_key: 'external_references.id'
  is_series: True
  child_pattern: '^(TCGA)[\-]\w+?\-[\w\-]{15,30}$'

pgxcohort:
  prefix: pgxcohort
  type: Progenetix cohort identifier
  pattern: '^(pgxcohort)[\-]\w+?$'
  scope: biosamples
  db_key: 'cohorts.id'
  is_series: False
