bycon_definition_files:
  - beacon_mappings
  - dataset_definitions
  - datatable_mappings
  - filter_definitions
  - geoloc_definitions
  - handover_definitions
  - interval_definitions
  - remap_definitions
  - services_defaults
  - services_mappings
  - variant_definitions

paths:
  web_temp_dir_abs:
    - /
    - Library
    - WebServer
    - Documents
    - Sites
    - progenetix
    - tmp

arg_defs_path:
  - config
  - command_line_args.yaml

schemas_root:
  - schemas

default_model_path:
  - schemas
  - models
  - json
  - progenetix-model

schemas_paths:
  description: >-
    path elements as list, from `schemas_root`
  items:
    - - models
      - json
      - progenetix-model
    # - - models
    #   - json
    #   - progenetix-model
    #   - common
    - - models
      - json
      - progenetix-service-schemas
    - - models
      - json
      - progenetix-database-schemas
    - - framework
      - json
      - common
    - - framework
      - json
      - configuration
    - - framework
      - json
      - requests
    - - framework
      - json
      - responses
    - - framework
      - json
      - responses
      - sections

form_list_pars:
  description: >-
    form parameters which are processed as list
  items:
    - start
    - end
    - datasetIds
    - filters
    - ids
    - biosampleIds
    - variantIds
    - individualIds
    - callsetIds
    - analysisIds
    - collationTypes

resource_urls:
  ncbi_geosoft: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?form=text&acc=
  ncbi_geoweb: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=
  europepmc_pmid: https://europepmc.org/article/MED/
  cellosaurus_web: https://web.expasy.org/cellosaurus/

# dataset_ids here are used for db management; the information used by Beacon
# is defined separately
dataset_ids:
  - progenetix
  # - cellosaurus
  # - 1000genomesDRAGEN

queried_collections:
  - biosamples
  - callsets
  - individuals
  - variants
  - collations
  - frequencymaps
  - publications

info_db: progenetix
collations_coll: collations
frequencymaps_coll: frequencymaps
collations_source: biosamples
ontologymaps_coll: ontologymaps
beacon_info_coll: beaconinfo
beacon_counts:
  individual_count:
    collection: individuals
    info_key: individuals
    h->o_key: individuals._id
  sample_count:
    collection: biosamples
    info_key: biosamples
    h->o_key: biosamples._id
  variant_count:
    collection: variants
    info_key: variants_distinct
    h->o_key: variants.variant_internal_id
  call_count:
    collection: variants
    info_key: variants
    h->o_key: variants._id
handover_coll: querybuffer
genespans_coll: genespans

filter_flags:
  logic: '$and'
  precision: exact #'start'
  include_descendant_terms: True

plot_pars:
  dotalpha: 0.2
  color_var_snv_hex: '#EE00DD'
  color_var_snv_rgb: '238,0,221'
  color_var_break_hex: '#EE00DD'
  color_var_break_rgb: '238,0,221'
  color_var_dup_hex: '#FFC633'
  color_var_dup_rgb: '255,198,51'
  color_var_del_hex: '#33A0FF'
  color_var_del_rgb: '51,160,255'
  color_var_loh_hex: '#9326de'
  color_var_loh_rgb: '147,38,222'
  color_var_amp_hex: '#FF6600'
  color_var_amp_rgb: '255,102,0'
  color_var_homoloss_hex: '#0033CC'
  color_var_homoloss_rgb: '0,51,204'
