io_params:
  biosample:
    biosample_id:
      db_key: id
      type: string
    individual_id:
      db_key: individual_id
      type: string
    callset_ids:
      db_key: info.callset_ids
      type: array
    pgx_legacy_sample_id:
      db_key: pgx_legacy_sample_id
      type: string
    legacy_ids:
      db_key: info.legacy_ids
      type: array
    description:
      db_key: description
      type: string
    histological_diagnosis_id:
      db_key: histological_diagnosis.id
      type: string
    histological_diagnosis_label:
      db_key: histological_diagnosis.label
      type: string
    icdo_morphology_id:
      db_key: icdo_morphology.id
      type: string
    icdo_morphology_label:
      db_key: icdo_morphology.label
      type: string
    icdo_topography_id:
      db_key: icdo_topography.id
      type: string
    icdo_topography_label:
      db_key: icdo_topography.label
      type: string
    sampled_tissue_id:
      db_key: sampled_tissue.id
      type: string
    sampled_tissue_id:
      db_key: sampled_tissue.label
      type: string
    tnm:
      db_key: info.tumor_tnm_text
      type: string
    stage:
      db_key: info.tumor_stage_text
      type: string
    grade:
      db_key: info.tumor_grade_text
      type: string
    age_iso:
      db_key: time_of_collection.age.iso8601duration
      type: string
    death:
      db_key: info.death
      type: string
    followup_state_id:
      db_key: followup_state.id
      default: 'EFO:0030039'
    followup_state_label:
      db_key: followup_state.label
      default: no followup status
    followup_time:
      db_key: followup_time
      type: string
    recurrence:
      db_key: info.recurrence
      type: string
    recurrence_time:
      db_key: info.recurrence_time
      type: string
    geoprov_city:
      db_key: provenance.geo_location.properties.city
      type: string
    geoprov_country:
      db_key: provenance.geo_location.properties.country
      type: string
    geoprov_iso_alpha3:
      db_key: provenance.geo_location.properties.ISO3166alpha3
      type: string
    geoprov_lat:
      db_key: provenance.geo_location.properties.latitude
      type: number
    geoprov_long:
      db_key: provenance.geo_location.properties.longitude
      type: number
    cnv_fraction:
      db_key: info.cnvstatistics.cnvfraction
      type: number
    cnv_del_fraction:
      db_key: info.cnvstatistics.delfraction
      type: number
    cnv_dup_fraction:
      db_key: info.cnvstatistics.dupfraction
      type: number
    cell_line:
      db_key: info.cell_line
      type: string
    experiment_id:
      db_key: analysis_info.experiment_id
      type: string
    series_id:
      db_key: analysis_info.series_id
      type: string
    platform_id:
      db_key: analysis_info.platform_id
      type: string
    cell_line_id:
      db_key: cell_line.id
      type: string
    cell_line_label:
      db_key: cell_line.label
      type: string

  individual:
    individual_id:
      db_key: id
      type: string
    legacy_ids:
      db_key: info.legacy_ids
      type: array
    sex_id:
      db_key: sex.id
      type: string
    sex_label:
      db_key: sex.label
      type: string
    data_use_conditions_id:
      db_key: data_use_conditions.id
      type: string
    data_use_conditions_label:
      db_key: data_use_conditions.label
      type: string
    # same as in biosample but different field
    histological_diagnosis_id:
      db_key: index_disease.disease_code.id
      type: string
    histological_diagnosis_label:
      db_key: index_disease.disease_code.label
      type: string
    index_disease_notes:
      db_key: index_disease.notes
      type: string
    auxiliary_disease_id:
      db_key: auxiliary_disease.disease_code.id
      type: string
    auxiliary_disease_label:
      db_key: auxiliary_disease.disease_code.label
      type: string
    auxiliary_disease_notes:
      db_key: auxiliary_disease.notes
      type: string
    geoprov_city:
      db_key: provenance.geo_location.properties.city
      type: string
    geoprov_country:
      db_key: provenance.geo_location.properties.country
      type: string
    geoprov_iso_alpha3:
      db_key: provenance.geo_location.properties.ISO3166alpha3
      type: string
    geoprov_lat:
      db_key: provenance.geo_location.properties.latitude
      type: float
    geoprov_long:
      db_key: provenance.geo_location.properties.longitude
      type: float
    cell_line_donation_id:
      db_key: info.cell_line_donation.id
      type: string
    cell_line_donation_label:
      db_key: info.cell_line_donation.label
      type: string

  analysis:
    analysis_id:
      db_key: id
      type: string
    biosample_id:
      db_key: biosample_id
      type: string
    individual_id:
      db_key: individual_id
      type: string
    legacy_ids:
      db_key: info.legacy_ids
      type: array
    experiment_id:
      db_key: analysis_info.experiment_id
      type: string
    series_id:
      db_key: analysis_info.series_id
      type: string
    platform_id:
      db_key: analysis_info.platform_id
      type: string
    data_provenance:
      db_key: info.data_provenance
      type: string

  variant:
    variant_id:
      db_key: id
      type: string
    variant_internal_id:
      db_key: variant_internal_id
      type: string
    reference_name:
      db_key: reference_name
      type: string
    start:
      db_key: start
      type: integer
    end:
      db_key: end
      type: integer
    variant_type:
      db_key: variant_type
      type: string
    reference_bases:
      db_key: reference_bases
      type: string
    alternate_bases:
      db_key: alternate_bases
      type: string

io_prefixes:

  biosample:
    external_references:
      type: array
      pres:
        - PMID
        - geo:GSM
        - geo:GSE
        - geo:GPL
        - cellosaurus
        - arrayexpress
        - cbioportal
    followup_state:
      type: string
      pre: EFO
    data_use_conditions:
      type: string
      pre: DUO

  individual: {}

  analysis:
    data_use_conditions:
      type: string
      pre: DUO

  variant: {}
  
