io_params:
  biosample:
    id:
      db_key: id
      type: string
    individual_id:
      db_key: individual_id
      type: string
    callset_ids:
      db_key: info.callset_ids
      type: array
    description:
      db_key: description
      type: string
    tnm:
      db_key: info.tumor_tnm_text
      type: string
    stage:
      db_key: info.tumor_stage_text
      type: string
    grade:
      db_key: info.tumor_grade_text
      type: string
    age_iso:
      db_key: time_of_collection.age
      type: string
    death:
      db_key: info.death
      type: string
    followup_months:
      db_key: info.followup_months
      type: string
    followup_time:
      db_key: followup_time
      type: string
    recurrence:
      db_key: info.recurrence
      type: string
    recurrence_time:
      db_key: info_recurrence_time
      type: string
    geoprov_label:
      db_key: provenance.geo_location.properties.label
      type: string
    geoprov_precision:
      db_key: provenance.geo_location.properties.precision
      type: string
    geoprov_city:
      db_key: provenance.geo_location.properties.city
      type: string
    geoprov_country:
      db_key: provenance.geo_location.properties.country
      type: string
    geoprov_iso_alpha3:
      db_key: provenance.geo_location.properties.ISO3166alpha3
      type: string
    geoprov_lat:
      db_key: provenance.geo_location.properties.latitude
      type: number
    geoprov_long:
      db_key: provenance.geo_location.properties.longitude
      type: number
    cnv_fraction:
      db_key: info.cnvstatistics.cnvfraction
      type: number
    cnv_del_fraction:
      db_key: info.cnvstatistics.delfraction
      type: number
    cnv_dup_fraction:
      db_key: info.cnvstatistics.dupfraction
      type: number
    cell_line:
      db_key: info.cell_line
      type: string
    legacy_ids:
      db_key: info.legacy_ids
      type: array
    individual_id:
      db_key: individual_id
      type: string

  individual:
    id:
      db_key: id
      type: string
    legacy_ids:
      db_key: info.legacy_ids
      type: array
    geoprov_label:
      db_key: provenance.geo_location.properties.label
      type: string
    geoprov_precision:
      db_key: provenance.geo_location.properties.precision
      type: string
    geoprov_city:
      db_key: provenance.geo_location.properties.city
      type: string
    geoprov_country:
      db_key: provenance.geo_location.properties.country
      type: string
    geoprov_iso_alpha3:
      db_key: provenance.geo_location.properties.ISO3166alpha3
      type: string
    geoprov_lat:
      db_key: provenance.geo_location.properties.latitude
      type: float
    geoprov_long:
      db_key: provenance.geo_location.properties.longitude
      type: float
    experiment_id:
      db_key: analysis_info.experiment_id
      type: string
    series_id:
      db_key: analysis_info.series_id
      type: string
    platform_id:
      db_key: analysis_info.platform_id
      type: string

  analysis:
    id:
      db_key: id
      type: string
    biosample_id:
      db_key: biosample_id
      type: string
    legacy_ids:
      db_key: info.legacy_ids
      type: array
    experiment_id:
      db_key: analysis_info.experiment_id
      type: string
    series_id:
      db_key: analysis_info.series_id
      type: string
    platform_id:
      db_key: analysis_info.platform_id
      type: string

  variantInSample:
    id:
      db_key: id
      type: string
    variant_internal_id:
      db_key: variant_internal_id
      type: string
    reference_name:
      db_key: reference_name
      type: string
    start:
      db_key: start
      type: integer
    end:
      db_key: end
      type: integer
    variant_type:
      db_key: variant_type
      type: string
    reference_bases:
      db_key: reference_bases
      type: string
    alternate_bases:
      db_key: alternate_bases
      type: string

io_prefixes:

  biosample:
    sampled_tissue:
      type: string
      pre: UBERON
    histological_diagnosis:
      type: string
      pre: NCIT
    icdo_morphology:
      type: string
      pre: icdom
    icdo_topography:
      type: string
      pre: icdot
    # biocharacteristics:
    #   type: array
    #   pres:
    #     - MONDO
    external_references:
      type: array
      pres:
        - PMID
        - geo:GSM
        - geo:GSE
        - geo:GPL
        - cellosaurus
        - arrayexpress
    followup_state:
      type: string
      pre: EFO
    data_use_conditions:
      type: string
      pre: DUO

  individual:
    sex:
      type: string
      pre: PATO
    data_use_conditions:
      type: string
      pre: DUO

  analysis:
    data_use_conditions:
      type: string
      pre: DUO

  variantInSample: {}
  
