const:
  tab_sep: "\t"
  dash_sep: "-"
info_db: progenetix
dataset_ids:
  - arraymap
  - progenetix
  - dipg
  - tcga
collections:
  - biosamples
  - callsets
  - individuals
  - variants
  - querybuffer
bio_prefixes:
  - icdom
  - icdot
  - NCIT
stats_collection: dbstats
plot_pars:
  dotalpha: 0.2
data_pars:
  dataset_id: arraymap
paths:
  status_matrix_file_label: matrix_status.tsv
  values_matrix_file_label: matrix_values.tsv
  web_server_root_abs: '/Library/WebServer/Documents'
  web_temp_dir_abs: '/Library/WebServer/Documents/tmp'