# Bio-Metadata
NCIT:
  name: "National Cancer Institute Thesaurus"
  url: "https://ncit.nci.nih.gov/"
  db_key: 'biocharacteristics.type.id'
  scopes:
    biosamples:
      default: 1
    individuals:
      default: 0
  pattern: '^NCIT\:C\d*?$'
  examples:
    - 'NCIT:C27676'
    - 'NCIT:C9325'

HP:
  name: "Human Phenotype Ontology"
  url: "https://hpo.jax.org/"
  db_key: 'biocharacteristics.type.id'
  scopes:
    biosamples:
      default: 0
    individuals:
      default: 1
  pattern: '^HP\:\d+?$'
  examples:
    - 'HP:0012209'

PATO:
  name: "Phenotypic Qualities Ontology"
  url: "http://obofoundry.org/ontology/pato.html"
  db_key: 'biocharacteristics.type.id'
  scopes:
    biosamples:
      default: 0
    individuals:
      default: 1
  pattern: '^PATO\:\d+?$'
  examples:
    - 'PATO:0020000'

EFO:
  name: "Experimental Factor Ontology"
  url: "https://www.ebi.ac.uk/efo/"
  db_key: 'biocharacteristics.type.id'
  scopes:
    biosamples:
      default: 1
    individuals:
      default: 0
  pattern: '^EFO\:\d+?$'
  examples:
    - 'EFO:0009656'

# Procedural Metadata

PMID:
  name: "NCBI PubMed"
  url: "https://www.ncbi.nlm.nih.gov/pubmed/"
  db_key: 'external_references.type.id'
  scopes:
    biosamples:
      default: 1
  pattern: '^(PMID)|(pubmed)\:\d+?$'
  examples:
    - 'PMID:28966033'
    - 'PMID:9405679'

geogse:
  name: "NCBI Gene Expression Omnibus Series"
  url: "https://www.ncbi.nlm.nih.gov/geo/"
  db_key: 'external_references.type.id'
  scopes:
    callsets:
      default: 0
    biosamples:
      default: 1
  pattern: '^geogse\-GSE\d+?$'
  examples:
    - 'geogse-GSM253289'

# geogsm:
#   name: "NCBI Gene Expression Omnibus Experiment" 
#   url: "https://www.ncbi.nlm.nih.gov/geo/"
#   db_key: 'external_references.type.id'
#   scopes:
#     callsets:
#       default: 0
#     biosamples:
#       default: 1
#   pattern: '^geogsm\-GSM\d+?$'
#   examples:
#     - 'geogsm-GSM253289'

geogpl:
  name: "NCBI Gene Expression Omnibus Platform"
  url: "https://www.ncbi.nlm.nih.gov/geo/"
  db_key: 'external_references.type.id'
  scopes:
    callsets:
      default: 0
    biosamples:
      default: 0
      default: 1
  pattern: '^geopl\-GPL\d+?$'
  examples:
    - 'geogpl-GPL6504'

cellosaurus:
  name: "Cellosaurus - a knowledge resource on cell lines"
  url: "https://web.expasy.org/cellosaurus/"
  db_key: 'external_references.type.id'
  scopes:
    callsets:
      default: 0
    biosamples:
      default: 1
  pattern: '^cellosaurus\:CVCL_\w+?$'
  examples:
    - 'cellosaurus:CVCL_1650'
    - 'cellosaurus:CVCL_0006'
