NCITgrade:
  name: "National Cancer Institute Thesaurus Disease Grade Qualifier"
  prefix: NCIT
  url: "https://ncit.nci.nih.gov/"
  db_key: 'tumor_grade.id'
  description: Disease Grade codes
  scope: biosamples
  pattern: '^NCIT(:C\d+?)?$'
  examples:
    - 'NCIT:C28078'
    - 'NCIT:C28080'

NCITstage:
  name: "National Cancer Institute Thesaurus Disease Stage Qualifier"
  prefix: NCIT
  url: "https://ncit.nci.nih.gov/"
  db_key: 'pathological_stage.id'
  description: Disease Stage codes
  scope: biosamples
  pattern: '^NCIT(:C\d+?)?$'
  examples:
    - 'NCIT:C27970'
    - 'NCIT:C27969'

NCITtnm:
  name: "National Cancer Institute Thesaurus Cancer TNM Finding"
  prefix: NCIT
  url: "https://ncit.nci.nih.gov/"
  db_key: 'pathological_tnm_findings.id'
  description: NCIT TNM codes
  scope: biosamples
  pattern: '^NCIT(:C\d+?)?$'
  examples:
    - 'NCIT:C48700'
    - 'NCIT:C48786'

# Bio-Metadata
NCIT:
  name: "National Cancer Institute Thesaurus neoplasias"
  prefix: NCIT
  url: "https://ncit.nci.nih.gov/"
  db_key: 'histological_diagnosis.id'
  scope: biosamples
  pattern: '^NCIT(:C\d+?)?$'
  examples:
    - 'NCIT:C27676'
    - 'NCIT:C9325'

UBERON:
  name: "Uberon cross-species anatomical structures ontology"
  prefix: UBERON
  url: "https://uberon.github.io"
  db_key: 'sampled_tissue.id'
  scope: biosamples
  pattern: '^UBERON(:\d*?)?$'
  examples:
    - 'UBERON:0000970'
    - 'UBERON:0035542'

HP:
  name: "Human Phenotype Ontology"
  prefix: HP
  url: "https://hpo.jax.org/"
  db_key: 'biocharacteristics.id'
  scope: individuals
  pattern: '^HP(:\d+?)?$'
  examples:
    - 'HP:0012209'

PATOsex:
  description: >
    PATO codes specific for genotypic sex...
  name: "Phenotypic Qualities Ontology"
  prefix: PATO
  url: "http://obofoundry.org/ontology/pato.html"
  db_key: 'sex.id'
  scope: individuals
  pattern: '^PATO(:002000[012])?$'
  examples:
    - 'PATO:0020000'

EFOfus:
  name: "EFO followup status classes"
  prefix: EFOfus
  url: "http://www.ebi.ac.uk/efo/EFO_0030038"
  db_key: 'followup_state.id'
  scope: biosamples
  pattern: '^EFO(:\d+?)?$'
  examples:
    - 'EFO:0030039'

EFOmaterial:
  name: "Experimental Factor Ontology"
  prefix: EFO
  url: "https://www.ebi.ac.uk/efo/"
  db_key: 'biosample_status.id'
  scope: biosamples
  pattern: '^(?:EFO)|(?:OBI):\d+?$'
  examples:
    - 'EFO:0009656'

icdom:
  name: "ICD-O 3 Morphologies (Progenetix transcription)"
  prefix: pgx
  url: https://progenetix.org/
  reference_root: https://progenetix.org/services/ids/
  db_key: 'icdo_morphology.id'
  scope: biosamples
  pattern: '^(?:pgx:)?icdom-\d{1,5}(-\d{1,5})?$'
  examples:
    - 'pgx:icdom-85003'
    - 'pgx:icdom-94403'

icdot:
  name: "ICD-O 3 Topographies (Progenetix transcription)"
  prefix: pgx
  url: "https://progenetix.org/"
  reference_root: https://progenetix.org/services/ids/
  db_key: 'icdo_topography.id'
  scope: biosamples
  pattern: '^(?:pgx:)?icdot-C\d\d?(\.\d)?$'
  examples:
    - 'pgx:icdot-C42.2'
    - 'pgx:icdot-C54.1'
    - 'pgx:icdot-C5'

# Procedural Metadata

PMID:
  name: "NCBI PubMed"
  prefix: PMID
  url: "https://www.ncbi.nlm.nih.gov/pubmed/"
  db_key: 'external_references.id'
  scope: biosamples
  pattern: '^PMID(:\d+?)?$'
  examples:
    - 'PMID:28966033'
    - 'PMID:9405679'

GEOseries:
  prefix: geo
  name: Gene Expression Omnibus series
  url: "https://www.ncbi.nlm.nih.gov/geo/"
  pattern: '^(?:geo:)?GSE\d+?$'
  scope: biosamples
  db_key: 'external_references.id'
  is_series: True
  child_pattern: '^(?:geo:)?GSM'
  examples:
    - geo:GSE19331

GEOplatform:
  prefix: geo
  name: Gene Expression Omnibus platform
  url: "https://www.ncbi.nlm.nih.gov/geo/"
  pattern: '^(?:geo:)?GPL\d+?$'
  scope: biosamples
  db_key: 'external_references.id'
  is_series: True
  child_pattern: '^(?:geo:)?GSM'
  examples:
    - geo:GPL6504
    - geo:GPL6801

GEOexperiment:
  prefix: geo
  url: "https://www.ncbi.nlm.nih.gov/geo/"
  name: Gene Expression Omnibus experiment
  pattern: '^(?:geo:)?GSM\d+?$'
  scope: biosamples
  db_key: 'external_references.id'
  is_series: False
  collationed: False
  examples:
    - geo:GSM253289

arrayexpress:
  name: "EBI ArrayExpress"
  prefix: arrayexpress
  url: "https://www.ncbi.nlm.nih.gov/geo/"
  db_key: 'external_references.id'
  scope: biosamples
  pattern: '^arrayexpress:[AEP]-\w{4}-\d+$'
  examples:
    - arrayexpress:E-MEXP-1008

TCGAproject:
  name: "The Cancer Genome Atlas"
  prefix: pgx
  url: "http://cancergenome.nih.gov"
  scope: biosamples
  pattern: '^(?:pgx:)TCGA-[\-\w]+?$'
  db_key: 'external_references.id'
  is_series: True
  child_pattern: '^(?:pgx:)?TCGA-\w+?\-[\w\-]{15,30}$'
  examples:
    - pgx:TCGA-000002fc-53a0-420e-b2aa-a40a358bba37

UBERON:
  name: Uberon cross-species anatomical structures ontology
  prefix: UBERON
  url: "http://uberon.org"
  scope: biosamples
  db_key: 'sampled_tissue.id'
  pattern: '^UBERON:\d+?$'
  examples:
    - UBERON:0000959
    - UBERON:0001869

cbioportal:
  name: "cBioPortal"
  prefix: cbioportal
  url: "https://www.cbioportal.org"
  scope: biosamples
  db_key: 'external_references.id'
  pattern: '^cbioportal:\w+?$'
  examples:
    - 'cbioportal:msk_impact_2017'

cellosaurus:
  name: "Cellosaurus - a knowledge resource on cell lines"
  prefix: cellosaurus
  url: "https://web.expasy.org/cellosaurus/"
  db_key: 'external_references.id'
  scope: biosamples
  pattern: '^cellosaurus:CVCL_\w+?$'
  examples:
    - 'cellosaurus:CVCL_1650'
    - 'cellosaurus:CVCL_0006'

pgxcohort:
  name: "Progenetix cohorts"
  prefix: pgx
  url: "https://arraymap.progenetix.org"
  db_key: 'cohorts.id'
  scope: biosamples
  pattern: '^pgx:cohort-\w+?$'
  examples:
    - 'pgx:cohort-arraymap'
    - 'pgx:cohort-TCGA'




