NCITgrade:
  name: "National Cancer Institute Thesaurus Disease Grade Qualifier"
  prefix: NCIT
  url: "https://ncit.nci.nih.gov/"
  db_key: 'tumor_grade.id'
  description: Disease Grade codes
  scope: biosamples
  pattern: '^NCIT([\:]C\d+?\-?)?$'
  pattern_strict: '^NCIT[\:]C\d+?$'
  examples:
    - 'NCIT:C28078'
    - 'NCIT:C28080'

NCITstage:
  name: "National Cancer Institute Thesaurus Disease Stage Qualifier"
  prefix: NCIT
  url: "https://ncit.nci.nih.gov/"
  db_key: 'pathological_stage.id'
  description: Pseudo-prefix recoding of Disease Stage codes
  scope: biosamples
  pattern: '^NCIT([\:]C\d+?\-?)?$'
  pattern_strict: '^NCIT[\:]C\d+?$'
  examples:
    - 'NCIT:C27970'
    - 'NCIT:C27969'

NCITtnm:
  name: "National Cancer Institute Thesaurus Cancer TNM Finding"
  prefix: NCIT
  url: "https://ncit.nci.nih.gov/"
  db_key: 'pathological_tnm_findings.id'
  description: Pseudo-prefix recoding of NCIT TNM codes
  scope: biosamples
  pattern: '^NCIT([\:]C\d+?\-?)?$'
  pattern_strict: '^NCIT[\:]C\d+?$'
  examples:
    - 'NCIT:C48700'
    - 'NCIT:C48786'

# Bio-Metadata
NCIT:
  name: "National Cancer Institute Thesaurus neoplasias"
  prefix: NCIT
  url: "https://ncit.nci.nih.gov/"
  db_key: 'histological_diagnosis.id'
  scope: biosamples
  pattern: '^NCIT([_\:]C\d+?\-?)?$'
  pattern_strict: '^NCIT[_\:]C\d+?$'
  examples:
    - 'NCIT:C27676'
    - 'NCIT:C9325'

UBERON:
  name: "Uberon cross-species anatomical structures ontology"
  prefix: UBERON
  url: "https://uberon.github.io"
  db_key: 'sampled_tissue.id'
  scope: biosamples
  pattern: '^UBERON([_\:]\d*?\-?)?$'
  pattern_strict: '^UBERON[_\:]\d+?$'
  examples:
    - 'UBERON:0000970'
    - 'UBERON:0035542'

HP:
  name: "Human Phenotype Ontology"
  prefix: HP
  url: "https://hpo.jax.org/"
  db_key: 'biocharacteristics.id'
  scope: individuals
  pattern: '^HP([_\:]\d+?\-?)?$'
  pattern_strict: '^HP[_\:]\d+?$'
  examples:
    - 'HP:0012209'

PATOsex:
  description: >
    PATO codes specific for genotypic sex...
  name: "Phenotypic Qualities Ontology"
  prefix: PATO
  url: "http://obofoundry.org/ontology/pato.html"
  db_key: 'sex.id'
  scope: individuals
  pattern: '^PATO([_\:]002000[012]\-?)?$'
  pattern_strict: '^PATO[_\:]002000[012]$'
  examples:
    - 'PATO:0020000'

EFOfus:
  name: "EFO followup status classes"
  prefix: EFOfus
  url: "http://www.ebi.ac.uk/efo/EFO_0030038"
  db_key: 'followup_state.id'
  scope: biosamples
  pattern: '^EFO([\-_\:]\d+?)?$'
  pattern_strict: '^EFO[\-_\:]\d+?$'
  examples:
    - 'EFO:0030039'

EFO:
  name: "Experimental Factor Ontology"
  prefix: EFO
  url: "https://www.ebi.ac.uk/efo/"
  db_key: 'biosample_status.id'
  scope: biosamples
  pattern: '^(?:EFO)|(?:OBI)([_\:]\d+?\-?)?$'
  pattern_strict: '^(?:EFO)|(?:OBI)[_\:]\d+?$'
  examples:
    - 'EFO:0009656'

icdom:
  name: "ICD-O 3 Morphologies (Progenetix)"
  prefix: icdom
  url: "https://progenetix.org/"
  db_key: 'icdo_morphology.id'
  scope: biosamples
  pattern: '^icdom(\-\d{1,5}(\-\d{1,5})?)?$'
  pattern_strict: '^icdom\-\d{5}$'
  examples:
    - 'icdom-85003'
    - 'icdom-94403'

icdot:
  name: "ICD-O 3 Topographies (Progenetix)"
  prefix: icdot
  url: "https://progenetix.org/"
  db_key: 'icdo_topography.id'
  scope: biosamples
  pattern: '^icdot(\-C\d\d?(\.\d)?\-?)?$'
  pattern_strict: '^icdot\-C\d\d?\.\d$'
  examples:
    - 'icdot-C42.2'
    - 'icdot-C54.1'
    - 'icdot-C5'

# Procedural Metadata

PMID:
  name: "NCBI PubMed"
  prefix: PMID
  url: "https://www.ncbi.nlm.nih.gov/pubmed/"
  db_key: 'external_references.id'
  scope: biosamples
  pattern: '^PMID([_\:]\d+?)?$'
  pattern_strict: '^PMID[_\:]\d{5,9}?$'
  examples:
    - 'PMID:28966033'
    - 'PMID:9405679'

geo:
  name: "NCBI Gene Expression Omnibus"
  prefix: geo
  url: "https://www.ncbi.nlm.nih.gov/geo/"
  db_key: 'external_references.id'
  scope: biosamples
  pattern: '^geo([_\:]G(PL|SM|SE|DS)\d+)?$'
  pattern_strict: '^geo[_\:]G(PL|SM|SE|DS)\d+?$'
  examples:
    - geo:GPL6504
    - geo:GSE19331
    - geo:GSM253289

arrayexpress:
  name: "EBI ArrayExpress"
  prefix: arrayexpress
  url: "https://www.ncbi.nlm.nih.gov/geo/"
  db_key: 'external_references.id'
  scope: biosamples
  pattern: '^arrayexpress([_\:][AEP]\-\w{4}\-\d+)?$'
  pattern_strict: '^arrayexpress[_\:][AEP]\-\w{4}\-\d+?$'
  examples:
    - arrayexpress:E-MEXP-1008

TCGAproject:
  name: "The Cancer Genome Atlas"
  prefix: TCGA
  url: "http://cancergenome.nih.gov"
  db_key: 'external_references.id'
  scope: biosamples
  db_key: 'external_references.id'
  pattern: '^TCGA([_\-][\-\w]+?)?$'
  pattern_strict: '^TCGA[_\-][\-\w]+?$'
  examples:
    - 'TCGA-000002fc-53a0-420e-b2aa-a40a358bba37'

cBP:
  name: "cBioPortal"
  prefix: cBP
  url: "https://www.cbioportal.org"
  db_key: 'external_references.id'
  scope: biosamples
  db_key: 'external_references.id'
  pattern: '^cBP(\-\w+?)?$'
  pattern_strict: '^cBP\-\w+?$'
  examples:
    - 'cBP-MSK_IMPACT_2017'

cellosaurus:
  name: "Cellosaurus - a knowledge resource on cell lines"
  prefix: cellosaurus
  url: "https://web.expasy.org/cellosaurus/"
  db_key: 'external_references.id'
  scope: biosamples
  pattern: '^cellosaurus([_\:]CVCL_\w+?)?$'
  pattern_strict: '^cellosaurus[_\:]CVCL_\w+?$'
  examples:
    - 'cellosaurus:CVCL_1650'
    - 'cellosaurus:CVCL_0006'

pgxcohort:
  name: "Progenetix cohorts"
  prefix: pgxcohort
  url: "https://arraymap.progenetix.org"
  db_key: 'cohorts.id'
  scope: biosamples
  pattern: '^pgxcohort(\-\w+?)?$'
  pattern_strict: '^pgxcohort\-\w+?$'
  examples:
    - 'pgxcohort-arraymap'
    - 'pgxcohort-TCGA'




