# Bio-Metadata
NCIT:
  name: "National Cancer Institute Thesaurus"
  url: "https://ncit.nci.nih.gov/"
  list_par: biocharacteristics
  scopes:
    biosamples:
      db_key: 'biocharacteristics.type.id'
      default: 1
    individuals:
      db_key: 'biocharacteristics.type.id'
  pattern: '^NCIT\:C\d+?$'
  examples:
    - 'NCIT:C27676'
    - 'NCIT:C9325'

HP:
  name: "Human Phenotype Ontology"
  url: "https://hpo.jax.org/"
  list_par: biocharacteristics
  scopes:
    biosamples:
      db_key: 'biocharacteristics.type.id'
    individuals:
      db_key: 'biocharacteristics.type.id'
      default: 1
  pattern: '^HP\:\d+?$'
  examples:
    - 'HP:0012209'

PATO:
  name: "Phenotypic Qualities Ontology"
  url: "http://obofoundry.org/ontology/pato.html"
  list_par: biocharacteristics
  scopes:
    biosamples:
      db_key: 'biocharacteristics.type.id'
    individuals:
      db_key: 'biocharacteristics.type.id'
      default: 1
  pattern: '^PATO\:\d+?$'
  examples:
    - 'PATO:0020000'

EFO:
  name: "Experimental Factor Ontology"
  url: "https://www.ebi.ac.uk/efo/"
  list_par: biocharacteristics
  scopes:
    biosamples:
      db_key: 'biocharacteristics.type.id'
      default: 1
    individuals:
      db_key: 'biocharacteristics.type.id'
  pattern: '^EFO\:\d+?$'
  examples:
    - 'EFO:0009656'

# Procedural Metadata

PMID:
  name: "PubMed"
  url: "https://www.ncbi.nlm.nih.gov/pubmed/"
  list_par: external_references
  scopes:
    biosamples:
      db_key: 'external_references.type.id'
      default: 1
  pattern: '^(PMID)|(pubmed)\:\d+?$'
  examples:
    - 'PMID:28966033'
    - 'PMID:9405679'

geogse:
  name: "NCBI Gene Expression Omnibus Series"
  url: "https://www.ncbi.nlm.nih.gov/geo/"
  list_par: external_references
  scopes:
    callsets:
      db_key: 'external_references.type.id'
    biosamples:
      db_key: 'external_references.type.id'
      default: 1
  pattern: '^geogse\-GSE\d+?$'
  examples:
    - 'geogse-GSM253289'

geogsm:
  name: "NCBI Gene Expression Omnibus Experiment" 
  url: "https://www.ncbi.nlm.nih.gov/geo/"
  list_par: external_references
  scopes:
    callsets:
      db_key: 'external_references.type.id'
    biosamples:
      db_key: 'external_references.type.id'
      default: 1
  pattern: '^geogsm\-GSM\d+?$'
  examples:
    - 'geogsm-GSM253289'

geogpl:
  name: "NCBI Gene Expression Omnibus Platform"
  url: "https://www.ncbi.nlm.nih.gov/geo/"
  list_par: external_references
  scopes:
    callsets:
      db_key: 'external_references.type.id'
    biosamples:
      db_key: 'external_references.type.id'
      default: 1
  pattern: '^geopl\-GPL\d+?$'
  examples:
    - 'geogpl-GPL6504'

cellosaurus:
  name: "Cellosaurus - a knowledge resource on cell lines"
  url: "https://web.expasy.org/cellosaurus/"
  list_par: external_references
  scopes:
    callsets:
      db_key: 'external_references.type.id'
    biosamples:
      db_key: 'external_references.type.id'
      default: 1
  pattern: '^cellosaurus\:CVCL_\w+?$'
  examples:
    - 'cellosaurus:CVCL_1650'
    - 'cellosaurus:CVCL_0006'
