geo_root: 'provenance.geo_location'
parameters:
  geo_latitude:
    type: float
    pattern: '^\-?\d+?(\.\d+?)?$'
  geo_longitude:
    type: float
    pattern: '^\-?\d+?(\.\d+?)?$'
  geo_distance:
    type: float
    pattern: '^\d+?(\.\d+?)?$'
    default: 10000
  city:
    type: string
    pattern: '^\w.{1,126}\w$'
  id:
    type: string
    pattern: '^\w+?(\:\:\w+?)?$'
  ISO3166alpha2:
    type: string
    pattern: '^\w\w$'
  ISO3166alpha3:
    type: string
    pattern: '^\w\w\w$'
request_types:
  geoquery:
    all_of:
      - geo_latitude
      - geo_longitude
      - geo_distance
  city:
    all_of:
      - city
  id:
    all_of:
      - id

map_params:
  plottype: map
  plotid: map
  canvas_w_px: 800
  canvas_h_px: 512
  bubble_stroke_color: '#dd6633'
  bubble_stroke_weight: 1
  bubble_fill_color: '#cc9966'
  bubble_opacity: 0.4
  tiles_source: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
  attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>'
  extra_JS: ""
  marker_type: 'circle'
  marker_scale: 200
  marker_max_r: 5000
  latitude: 10.0
  longitude: 35.0
  zoom: 2
  zoom_min: 2
  zoom_max: 12
  head: >-
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css" integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ==" crossorigin="" />

