geo_root: 'provenance.geo_location'
parameters:
  geo_latitude:
    type: float
    pattern: '^\-?\d+?(\.\d+?)?$'
  geo_longitude:
    type: float
    pattern: '^\-?\d+?(\.\d+?)?$'
  geo_distance:
    type: float
    pattern: '^\d+?(\.\d+?)?$'
    default: 10000
  city:
    type: string
    pattern: '^\w.{1,126}\w$'
  id:
    type: string
    pattern: '^\w+?(\:\:\w+?)?$'
request_types:
  geoquery:
    all_of:
      - geo_latitude
      - geo_longitude
      - geo_distance
  city:
    all_of:
      - city
  id:
    all_of:
      - id
