geo_root: 'provenance.geo_location'
parameters:
  geolatitude:
    type: float
    pattern: '^\-?\d+?(\.\d+?)?$'
  geolongitude:
    type: float
    pattern: '^\-?\d+?(\.\d+?)?$'
  geodistance:
    type: float
    pattern: '^\d+?(\.\d+?)?$'
    default: 10000
  city:
    type: string
    pattern: '^\w.{1,126}\w$'
  id:
    type: string
    pattern: '^\w+?(\:\:\w+?)?$'
request_types:
  geoquery:
    all_of:
      - geolatitude
      - geolongitude
      - geodistance
  city:
    all_of:
      - city
  id:
    all_of:
      - id
