genome_binning:
  default: 1000000
  1Mb: 1000000
  100kb: 100000
  10kb: 10000
  cytobands: 4000000    # fallback to numeric value

interval_min_fraction: 0.01

chromosomes:            # defined in order & as strings
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
  - "15"
  - "16"
  - "17"
  - "18"
  - "19"
  - "20"
  - "21"
  - "22"
  - "X"
  - "Y"

cytobands:
  pattern: ^(chro?)?([12]?[\dXY])([pq]((ter)|(cen)|([1-4]([0-8](\.\d\d*?)?)?)?))?\-?([pq]((ter)|(cen)|([1-4]([0-8](\.\d\d*?)?)?)?))?$
