genome_binning:
  default: 1000000
  1Mb: 1000000
  2Mb: 2000000
  3Mb: 3000000
  4Mb: 4000000
  5Mb: 5000000
  7Mb: 7000000
  10Mb: 10000000
  15Mb: 15000000
  20Mb: 20000000
  100kb: 100000
  10kb: 10000
  cytobands: 4000000    # fallback to numeric value
genome_path_ids:        # the keys are stemmed & lower cased programmatically
  grch38: grch38
  grch37: hg19
  ncbi36: hg18
  ncbi35: hg17
  ncbi34: hg16
  mm8: mm8
  mm9: mm9
  msarhar1: mSarHar1.11
  zf7: zf7
terminal_intervals_soft_expansion: 100000
interval_min_fraction: 0.001
chromosomes:            # defined in order & as strings
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
  - "15"
  - "16"
  - "17"
  - "18"
  - "19"
  - "20"
  - "21"
  - "22"
  - "X"
  - "Y"

cytobands:
  pattern: ^(chro?)?([12]?[\dXY])([pq]((ter)|(cen)|([1-4]([0-8](\.\d\d*?)?)?)?))?\-?([pq]((ter)|(cen)|([1-4]([0-8](\.\d\d*?)?)?)?))?$
