---
line_patterns:
  pathological_stage:
    - '^.*?stage[^\w]+?(\w+?)(:?[^\w]|$)'
  tumor_grade:
    - '^.*?grade[^\w]+?(\w+?)(:?[^\w]|$)'


ontology_remaps:
  pathological_tnm_findings:
    search_fields:
      - info.tnm
    class_patterns:
      - id: "TNM-C48699"
        label: "M0 Stage Finding"
        pattern: "^.*?T0[^abcd]*?$"
      - id: "TNM-C95956"
        label: "cM0 (i+) Stage Finding"
        pattern: "^.*?cM0.*?$"
      - id: "TNM-C48701"
        label: "M1a Stage Finding"
        pattern: "^.*?M1a.*?$"
      - id: "TNM-C48702"
        label: "M1b Stage Finding"
        pattern: "^.*?M1b.*?$"
      - id: "TNM-C48703"
        label: "M1c Stage Finding"
        pattern: "^.*?M1c.*?$"
      - id: "TNM-C48700"
        label: "M1 Stage Finding"
        pattern: "^.*?M1[^abcd]*?$"
      - id: "TNM-C48704"
        label: "MX Stage Finding"
        pattern: "^.*?MX[^abcd]*?$"
      - id: "TNM-C48705"
        label: "N0 Stage Finding"
        pattern: "^.*?N0[^abcd]*?$"
      - id: "TNM-C48706"
        label: "N1 Stage Finding"
        pattern: "^.*?N1[^abciI]*?$"
      - id: "TNM-C48707"
        label: "N1a Stage Finding"
        pattern: "^.*?N1a.*?$"
      - id: "TNM-C48708"
        label: "N1b Stage Finding"
        pattern: "^.*?N1b[^I]*?$"
      - id: "TNM-C95929"
        label: "N1bI Stage Finding"
        pattern: "^.*?N1bI[^IV]*?$"
      - id: "TNM-C95935"
        label: "N1bII Stage Finding"
        pattern: "^.*?N1bII[^I]*?$"
      - id: "TNM-C95936"
        label: "N1bIII Stage Finding"
        pattern: "^.*?N1bIII.*?$"
      - id: "TNM-C95937"
        label: "N1bIV Stage Finding"
        pattern: "^.*?N1bIV.*?$"
      - id: "TNM-C48709"
        label: "N1c Stage Finding"
        pattern: "^.*?N1c.*?$"
      - id: "TNM-C95955"
        label: "N1mi Stage Finding"
        pattern: "^.*?N1mi.*?$"
      - id: "TNM-C48786"
        label: "N2 Stage Finding"
        pattern: "^.*?N2[^abciI]*?$"
      - id: "TNM-C48711"
        label: "N2a Stage Finding"
        pattern: "^.*?N2a.*?$"
      - id: "TNM-C48712"
        label: "N2b Stage Finding"
        pattern: "^.*?N2b.*?$"
      - id: "TNM-C48713"
        label: "N2c Stage Finding"
        pattern: "^.*?N2c.*?$"
      - id: "TNM-C48714"
        label: "N3 Stage Finding"
        pattern: "^.*?N1[^abciI]*?$"
      - id: "TNM-C48715"
        label: "N3a Stage Finding"
        pattern: "^.*?N3a.*?$"
      - id: "TNM-C48716"
        label: "N3b Stage Finding"
        pattern: "^.*?N3b.*?$"
      - id: "TNM-C48717"
        label: "N3c Stage Finding"
        pattern: "^.*?N3c.*?$"
      - id: "TNM-C48718"
        label: "NX Stage Finding"
        pattern: "^.*?NX.*?$"
      - id: "TNM-C96026"
        label: "N4 Stage Finding"
        pattern: "^.*?N4.*?$"
      - id: "TNM-C132010"
        label: "T5 Stage Finding"
        pattern: "^.*?T5.*?$"
      - id: "TNM-C48719"
        label: "T0 Stage Finding"
        pattern: "^.*?T0.*?$"
      - id: "TNM-C48720"
        label: "T1 Stage Finding"
        pattern: "^.*?T1[^abcdi]*?$"
      - id: "TNM-C48721"
        label: "T1a Stage Finding"
        pattern: "^.*?T1a.*?$"
      - id: "TNM-C48722"
        label: "T1b Stage Finding"
        pattern: "^.*?T1b.*?$"
      - id: "TNM-C48723"
        label: "T1c Stage Finding"
        pattern: "^.*?T1c.*?$"
      - id: "TNM-C95805"
        label: "T1b Stage Finding"
        pattern: "^.*?T1mi.*?$"
      - id: "TNM-C48724"
        label: "T2 Stage Finding"
        pattern: "^.*?T2[^abcdi]*?$"
      - id: "TNM-C48725"
        label: "T2a Stage Finding"
        pattern: "^.*?T2a.*?$"
      - id: "TNM-C48726"
        label: "T2b Stage Finding"
        pattern: "^.*?T2b.*?$"
      - id: "TNM-C48727"
        label: "T2c Stage Finding"
        pattern: "^.*?T2c.*?$"
      - id: "TNM-C148411"
        label: "T2d Stage Finding"
        pattern: "^.*?T2d.*?$"
      - id: "TNM-C48728"
        label: "T3 Stage Finding"
        pattern: "^.*?T3[^abcd]*?$"
      - id: "TNM-C48729"
        label: "T3a Stage Finding"
        pattern: "^.*?T3a.*?$"
      - id: "TNM-C48730"
        label: "T3b Stage Finding"
        pattern: "^.*?T3b.*?$"
      - id: "TNM-C48731"
        label: "T3c Stage Finding"
        pattern: "^.*?T3c.*?$"
      - id: "TNM-C148412"
        label: "T3d Stage Finding"
        pattern: "^.*?T3d.*?$"
      - id: "TNM-C48732"
        label: "T4 Stage Finding"
        pattern: "^.*?T4[^abcd]*?$"
      - id: "TNM-C48733"
        label: "T2a Stage Finding"
        pattern: "^.*?T2a.*?$"
      - id: "TNM-C48734"
        label: "T4b Stage Finding"
        pattern: "^.*?T4b.*?$"
      - id: "TNM-C48735"
        label: "T4c Stage Finding"
        pattern: "^.*?T4c.*?$"
      - id: "TNM-C48736"
        label: "T4d Stage Finding"
        pattern: "^.*?T4d.*?$"
      - id: "TNM-C48737"
        label: "TX Stage Finding"
        pattern: "^.*?TX.*?$"
      - id: "TNM-C48738"
        label: "Tis Stage Finding"
        pattern: "^.*?Tis.*?$"
      - id: "TNM-C96025"
        label: "T4d Stage Finding"
        pattern: "^.*?Ta.*?$"

  pathological_stage:
    search_fields:
      - info.tumor_stage
    class_patterns:
      - id: "NCITstage-C27966"
        label: "Stage I"
        pattern: "^i[^iabcd]*?$"
      - id: "NCITstage-C27975"
        label: "Stage Ia"
        pattern: "^ia[^i1234]*?$"
      - id: "NCITstage-C27966"
        label: "Stage Ia3"
        pattern: "^ia3[^i]*?$"
      - id: "NCITstage-C279836"
        label: "Stage Ia1"
        pattern: "^ia1[^i]*?$"
      - id: "NCITstage-C27984"
        label: "Stage Ia2"
        pattern: "^ia2[^i]*?$"
      - id: "NCITstage-C27976"
        label: "Stage Ib"
        pattern: "^ib[^i1234]*?$"
      - id: "NCITstage-C28052"
        label: "Stage Ib1"
        pattern: "^ib1[^i]*?$"
      - id: "NCITstage-C28053"
        label: "Stage Ib2"
        pattern: "^ib2[^i]*?$"
      - id: "NCITstage-C28053"
        label: "Stage Ic"
        pattern: "^ic[^i1234]*?$"   
      - id: "NCITstage-C27970"
        label: "Stage III"
        pattern: "^iii[^iabcd]*?$"
      - id: "NCITstage-C137676"
        label: "Stage IIID"
        pattern: "^iiid[^iabc]*?$"
      - id: "NCITstage-C27977"
        label: "Stage IIIa"
        pattern: "^iiia[^123ibcd]*?$"
      - id: "NCITstage-C139980"
        label: "Stage IIIa1"
        pattern: "^iiia1[^23ibcd]*?$"
      - id: "NCITstage-C139981"
        label: "Stage IIIa2"
        pattern: "^iiia2[^13ibcd]*?$"
      - id: "NCITstage-C27978"
        label: "Stage IIIb"
        pattern: "^iiib[^123ibcd]*?$"  
      - id: "NCITstage-C27982"
        label: "Stage IIIc"
        pattern: "^iiic[^123iabd]*?$"    
      - id: "NCITstage-C95179"
        label: "Stage IIIc1"
        pattern: "^iiic1[^23iabd]*?$"  
      - id: "NCITstage-C95180"
        label: "Stage IIIc2"
        pattern: "^iiic2[^13iabd]*?$" 
      - id: "NCITstage-C27971"
        label: "Stage IV"
        pattern: "^iv[^123isabcd]*?$"  
      - id: "NCITstage-C27972"
        label: "Stage IVS"
        pattern: "^ivs[^123iabcd]*?$"   
      - id: "NCITstage-C27979"
        label: "Stage IVa"
        pattern: "^iva[^123isbcd]*?$"  
      - id: "NCITstage-C141344"
        label: "Stage IVa1"
        pattern: "^iva1[^23isbcd]*?$"  
      - id: "NCITstage-C141345"
        label: "Stage IVa2"
        pattern: "^iva2[^13isbcd]*?$"  
      - id: "NCITstage-C27980"
        label: "Stage IVb"
        pattern: "^ivb[^123isacd]*?$"   
      - id: "NCITstage-C28055"
        label: "Stage IVc"
        pattern: "^ivc[^123isbad]*?$"  
      - id: "NCITstage-C27973"
        label: "Stage V"
        pattern: "^v[^123isabcd]*?$"  
      - id: "NCITstage-C28051"
        label: "Stage 0"
        pattern: "^0[^123isabcd]*?$"    
      - id: "NCITstage-C27964"
        label: "Stage 0a"
        pattern: "^0a[^123isbcd]*?$"  
      - id: "NCITstage-C27965"
        label: "Stage 0is"
        pattern: "^0is[^123isabcd]*?$"   
      - id: "NCITstage-C28054"
        label: "Stage II"
        pattern: "^ii[^123isabcd]*?$"  
      - id: "NCITstage-C27967"
        label: "Stage IIa"
        pattern: "^iia[^123isabcd]*?$"   
      - id: "NCITstage-C95177"
        label: "Stage IIa1"
        pattern: "^iia1[^23isabcd]*?$"   
      - id: "NCITstage-C95178"
        label: "Stage IIa2"
        pattern: "^iia2[^123isabcd]*?$"   
      - id: "NCITstage-C95178"
        label: "Stage IIa2"
        pattern: "^iia2[^123isabcd]*?$"  
      - id: "NCITstage-C27968"
        label: "Stage IIb"
        pattern: "^iib[^123isabcd]*?$"
      - id: "NCITstage-C27969"
        label: "Stage IIc"
        pattern: "^iic[^123isabcd]*?$"  
      - id: "NCITstage-C95177"
        label: "Stage IIa1"
        pattern: "^iia1[^123isabcd]*?$"
      - id: "NCITstage-C95178"
        label: "Stage IIa2"
        pattern: "^iia2[^123isabcd]*?$"
       
