service_names:
  root_path: info
  info: info
  filtering_terms: filteringTerms
  filteringTerms: filteringTerms
  datasets: datasets
  biosamples: biosamples
  individuals: individuals
  g_variants: variants
  variants: variants

