web_server_domain: http://bycon.progenetix.org
test_server_domain: http://bycon.progenetix.test
web_handover_domain: http://progenetix.org
test_handover_domain: http://progenetix.test
# dataset_ids here are used for db management; the information used by Beacon
# is defined separately
dataset_ids:
  - arraymap
  - progenetix
  - cellosaurus
collections:
  - biosamples
  - callsets
  - individuals
  - variants
  - collations
  - publications
collationed:
  geo:
    pattern: '^(geo)[:]((GSE)|(GPL))'
    is_series: True
    child_pattern: '^(geo)[:]GSM'
  NCIT:
    pattern: '^(NCIT)[:]C'
    is_series: False
  icdom:
    pattern: '^(icdom)[\-]\d'
    is_series: False
  icdot:
    pattern: '^(icdot)[\-]C'
    is_series: False
  cellosaurus:
    pattern: '^(cellosaurus)[:]CVCL'
    is_series: False
  PMID:
    pattern: '^(PMID)[:]\d'
    is_series: False
  UBERON:
    pattern: '^(UBERON)[:]\d'
    is_series: False
  cBP:
    pattern: '^(cBP)[\-]\w'
    is_series: False
  TCGA:
    pattern: '^(TCGA)[\-][\w\-]{2,20}$'
    is_series: True
    child_pattern: '^(TCGA)[\-]\w+?\-[\w\-]{15,30}$'
collations_coll: collations
collations_source: biosamples
ontologymaps_coll: ontologymaps
info_db: progenetix
beacon_info_coll: "beaconinfo"
beacon_info_count_labels:
  biosamples: "sampleCount"
  individuals: "individualCount"
  variants: "callCount"
  variants_distinct: "variantCount"
handover_coll: querybuffer
genespans_coll: genespans
filter_flags:
  logic: '$and'
  precision: exact #'start'
response_object_schema:
  parameters: { }
  data: [ ]
  response_type: ""
  errors: [ ]
  warnings: [ ]
plot_pars:
  dotalpha: 0.2
  color_var_snv_hex: '#EE00DD'
  color_var_snv_rgb: '238,0,221'
  color_var_break_hex: '#EE00DD'
  color_var_break_rgb: '238,0,221'
  color_var_dup_hex: '#FFC633'
  color_var_dup_rgb: '255,198,51'
  color_var_del_hex: '#33A0FF'
  color_var_del_rgb: '51,160,255'
  color_var_loh_hex: '#9326de'
  color_var_loh_rgb: '147,38,222'
  color_var_amp_hex: '#FF6600'
  color_var_amp_rgb: '255,102,0'
  color_var_homoloss_hex: '#0033CC'
  color_var_homoloss_rgb: '0,51,204'
paths:
  web_server_root_abs:
    - /
    - Library
    - WebServer
    - Documents
  web_temp_dir_abs:
    - /
    - Library
    - WebServer
    - Documents
    - tmp
