# Bio-Metadata
NCIT:
  name: "National Cancer Institute Thesaurus"
  url: "https://ncit.nci.nih.gov/"
  db_key: 'biocharacteristics.type.id'
  scopes:
    biosamples:
      default: 1
    individuals:
      default: 0
  pattern: '^NCIT(\:C\d+?\-?)?$'
  pattern_strict: '^NCIT\:C\d+?$'
  examples:
    - 'NCIT:C27676'
    - 'NCIT:C9325'
  collation: biosubsets

UBERON:
  name: "Uberon cross-species anatomical structures ontology"
  url: "https://uberon.github.io"
  db_key: 'biocharacteristics.type.id'
  scopes:
    biosamples:
      default: 1
  pattern: '^UBERON(\:\d*?\-?)?$'
  pattern_strict: '^UBERON\:\d+?$'
  examples:
    - 'UBERON:0000970'
    - 'UBERON:0035542'
  collation: biosubsets

MONDO:
  name: "Mondo Disease Ontology"
  url: "https://mondo.monarchinitiative.org"
  db_key: 'biocharacteristics.type.id'
  scopes:
    biosamples:
      default: 1
    individuals:
      default: 0
  pattern: '^MONDO([\:_]\d*?\-?)?$'
  pattern_strict: '^MONDO[\:_]\d+?$'
  examples:
    - 'MONDO:0002974'
    - 'MONDO:0012301'
  collation: biosubsets

HP:
  name: "Human Phenotype Ontology"
  url: "https://hpo.jax.org/"
  db_key: 'biocharacteristics.type.id'
  scopes:
    biosamples:
      default: 0
    individuals:
      default: 1
  pattern: '^HP(\:\d+?\-?)?$'
  pattern_strict: '^HP\:\d+?$'
  examples:
    - 'HP:0012209'
  collation: biosubsets

PATO:
  name: "Phenotypic Qualities Ontology"
  url: "http://obofoundry.org/ontology/pato.html"
  db_key: 'biocharacteristics.type.id'
  scopes:
    biosamples:
      default: 0
    individuals:
      default: 1
  pattern: '^PATO(\:\d+?\-?)?$'
  pattern_strict: '^PATO\:\d+?$'
  examples:
    - 'PATO:0020000'
  collation: biosubsets

EFO:
  name: "Experimental Factor Ontology"
  url: "https://www.ebi.ac.uk/efo/"
  db_key: 'provenance.material.type.id'
  scopes:
    biosamples:
      default: 1
    individuals:
      default: 0
  pattern: '^EFO(\:\d+?\-?)?$'
  pattern_strict: '^EFO\:\d+?$'
  examples:
  collation: biosubsets
    - 'EFO:0009656'
  collation: biosubsets

icdom:
  name: "ICD-O 3 Morphologies (Progenetix)"
  url: "https://progenetix.org/"
  db_key: 'biocharacteristics.type.id'
  scopes:
    biosamples:
      default: 1
  pattern: '^icdom(\-\d{1,5}(\-\d{1,5})?)?$'
  pattern_strict: '^icdom\-\d{5}$'
  examples:
    - 'icdom-85003'
    - 'icdom-94403'
  collation: biosubsets

icdot:
  name: "ICD-O 3 Topographies (Progenetix)"
  url: "https://progenetix.org/"
  db_key: 'biocharacteristics.type.id'
  scopes:
    biosamples:
      default: 1
  pattern: '^icdot(\-C\d\d?(\.\d)?\-?)?$'
  pattern_strict: '^icdot\-C\d\d?\.\d$'
  examples:
    - 'icdot-C42.2'
    - 'icdot-C54.1'
    - 'icdot-C5'
  collation: biosubsets

# Procedural Metadata

PMID:
  name: "NCBI PubMed"
  url: "https://www.ncbi.nlm.nih.gov/pubmed/"
  db_key: 'external_references.type.id'
  scopes:
    biosamples:
      default: 1
  pattern: '^PMID(\:\d+?)?$'
  pattern_strict: '^PMID\:\d{5,9}?$'
  examples:
    - 'PMID:28966033'
    - 'PMID:9405679'
  collation: datacollections

geo:
  name: "NCBI Gene Expression Omnibus"
  url: "https://www.ncbi.nlm.nih.gov/geo/"
  db_key: 'external_references.type.id'
  scopes:
    callsets:
      default: 0
    biosamples:
      default: 1
  pattern: '^geo([\-\:]G(PL|SM|SE|DS)\d+)?$'
  pattern_strict: '^geo[\-\:]G(PL|SM|SE|DS)\d+?$'
  examples:
    - geo:GPL6504
    - geo:GSE19331
    - geo:GSM253289
  collation: datacollections

arrayexpress:
  name: "EBI ArrayExpress"
  url: "https://www.ncbi.nlm.nih.gov/geo/"
  db_key: 'external_references.type.id'
  scopes:
    callsets:
      default: 0
    biosamples:
      default: 1
  pattern: '^arrayexpress([\-\:][AEP]\-\w{4}\-\d+)?$'
  pattern_strict: '^arrayexpress[\-\:][AEP]\-\w{4}\-\d+?$'
  examples:
    - geo:GPL6504
    - geo:GSE19331
    - geo:GSM253289
  collation: datacollections

tcga:
  name: "The Cancer Genome Atlas"
  url: "http://cancergenome.nih.gov"
  db_key: 'external_references.type.id'
  scopes:
    callsets:
      default: 0
    biosamples:
      default: 1
    individuals:
      db_key: 'external_references.type.id'
  pattern: '^tcga(:[\-\w]+?)?$'
  pattern_strict: '^tcga:[\-\w]+?$'
  examples:
    - 'tcga:000002fc-53a0-420e-b2aa-a40a358bba37'
  collation: None


cellosaurus:
  name: "Cellosaurus - a knowledge resource on cell lines"
  url: "https://web.expasy.org/cellosaurus/"
  db_key: 'external_references.type.id'
  scopes:
    callsets:
      default: 0
    biosamples:
      default: 1
  pattern: '^cellosaurus(\:CVCL_\w+?)?$'
  pattern_strict: '^cellosaurus\:CVCL_\w+?$'
  examples:
    - 'cellosaurus:CVCL_1650'
    - 'cellosaurus:CVCL_0006'
  collation: datacollections
