bycon_definition_files:
  - config
  - dataset_definitions
  - filter_definitions
defaults:
  method: ""
meta:
  beacon_id: org.progenetix
  response_type: InfoResponse
  returned_schemas:
    FilteringTerm: "https://beacon-project.io/schemas/beacon-v2/current/FilteringTerm.json"
  info: >
    The latest filtering terms payload can be accessed in `response.results`.
methods:
  counts:
    - counts
  filtering_terms:
    - counts
    - filtering_terms
