"$schema": https://json-schema.org/draft/2020-12/schema
"$id": https://progenetix.org/services/schemas/InteractorFields/v2021-03-07
title: InteractorFields
meta:
  $ref: 'byconBeaconMeta.yaml#/properties'
description: |
  Fields to filter by interactor.
type: object
properties:
  id:
    description: |
      Id of the interactor to display.
    type: string
  individualId:
    description: |
      `individualId` of the interactor(s) to display.
    type: string
