bycon_definition_files:
  - config
  - beacon_info
  - beacon_mappings
  - dataset_definitions
  - datatable_mappings
  - filter_definitions
  - geoloc_definitions
  - handover_definitions
  - interval_definitions
  - variant_definitions
defaults:
  dataset_ids:
    - progenetix
  response_type: variant
  response_schema: beaconResultsetsResponse
  genome_binning: 1Mb
  test_document_id: pgxvar-5bab576a727983b2e00b8d32
meta:
  returned_schemas:
    - entity_type: variant
      schema: https://progenetix.org/services/schemas/genomicVariation
  received_request_summary:
    requested_granularity: record
    include_resultset_responses: HIT
    requested_schemas:
      - entity_type: variant
        schema: https://progenetix.org/services/schemas/genomicVariation
  returned_granularity: record
  info: >
    The main variants payload can be accessed in `resultSets`.
all_variants_methods:
  - callsetsvariants
  - callsetspgxseg
response_types:
  - variant
  - individual
  - biosample
include_resultset_responses:
  - HIT
  - ALL
  - NONE
