defaults:
  dataset_ids:
    - progenetix
  response_type: variantInSample
  response_schema: beaconResultsetsResponse
  genome_binning: 1Mb
meta:
  returned_schemas:
    Variant: https://progenetix.org/services/schemas/Variant/
  info: >
    The main variants payload can be accessed in `resultSets`.
bycon_definition_files:
  - config
  - beacon_info
  - beacon_mappings
  - dataset_definitions
  - datatable_mappings
  - filter_definitions
  - geoloc_definitions
  - handover_definitions
  - interval_definitions
  - variant_definitions
all_variants_methods:
  - callsetsvariants
  - callsetspgxseg
response_types:
  - variantInSample
  - variantInterpretation
  - individual
  - biosample
