bycon_definition_files:
  - config
  - beacon
  - dataset_definitions
  - filter_definitions
  - geoloc_definitions
  - variant_definitions
  - handover_definitions
  - service_info
  - beacon_info
methods:
  - variants
  - biosamples
