bycon_definition_files:
  - config
  - filter_definitions
  - dataset_definitions
collection_name: collations
defaults:
  dataset_ids:
    - progenetix
  method: children
  filters:
    - NCIT
    - icdom
    - icdot
    - cellosaurus
meta:
  response_type: collations
  returned_schemas:
    Collation: https://progenetix.org/services/schemas/Collation/
  info: >
    The main collations payload can be accessed in `results`.
integer_keys:
  - count
  - code_matches
methods:
  children:
    - id
    - label
    - count
    - child_terms
    - code_matches
  paths:
    - id
    - label
    - count
    - code_matches
    - child_terms
    - hierarchy_paths
  counts:
    - id
    - label
    - count
    - code_matches
  codematches:
    - id
    - label
    - code_matches
  cnvFrequencies:
    - id
    - label
    - frequencymaps
  codes:
    - id
    - label
  ids:
    - id
collationed:
  geo:
    pattern: '^(geo)[:]((GSE)|(GPL))'
    is_series: True
    child_pattern: '^(geo)[:]GSM'
  NCIT:
    pattern: '^(NCIT)[:]C'
    is_series: False
  icdom:
    pattern: '^(icdom)[\-]\d'
    is_series: False
  icdot:
    pattern: '^(icdot)[\-]C'
    is_series: False
  cellosaurus:
    pattern: '^(cellosaurus)[:]CVCL'
    is_series: False
  PMID:
    pattern: '^(PMID)[:]\d'
    is_series: False
  UBERON:
    pattern: '^(UBERON)[:]\d'
    is_series: False
  cBP:
    pattern: '^(cBP)[\-]\w'
    is_series: False
  TCGA:
    pattern: '^(TCGA)[\-][\w\-]{2,20}$'
    is_series: True
    child_pattern: '^(TCGA)[\-]\w+?\-[\w\-]{15,30}$'
  pgxcohort:
    pattern: '^(pgxcohort)[\-]\w+?$'
    is_series: False
