bycon_definition_files:
  - filter_definitions
  - dataset_definitions
  - services_mappings
  - beacon_mappings
collection_name: collations
defaults:
  dataset_ids:
    - progenetix
  method: counts
  filters:
    - NCIT
    - icdom
    - icdot
    - cellosaurus
  response_entity_id: collation

meta:
  info: >
    The main collations payload can be accessed in `response.results`.
integer_keys:
  - count
  - code_matches
method_keys:
  details: []
  child_terms:
    - id
    - label
    - count
    - child_terms
    - code_matches
    - collation_type
    - type
    - reference
  paths:
    - id
    - label
    - count
    - code_matches
    - child_terms
    - hierarchy_paths
    - collation_type
    - type
    - reference
  counts:
    - id
    - label
    - count
    - code_matches
    - collation_type
    - type
    - reference
  codematches:
    - id
    - label
    - code_matches
    - collation_type
    - type
    - reference
  codes:
    - id
    - label
  ids:
    - id
