bycon_definition_files:
  - config
  - filter_definitions
defaults:
  dataset_ids:
    - progenetix
  method: children
  filters:
    - NCIT
    - icdom
    - icdot
    - cellosaurus
meta:
  response_type: collations
  returned_schemas:
    Collation: https://progenetix.org/services/schemas/Collation/
  info: >
    The main collations payload can be accessed in `response.results`.
methods:
  children:
    - id
    - label
    - count
    - child_terms
    - code_matches
  paths:
    - id
    - label
    - count
    - code_matches
    - child_terms
    - hierarchy_paths
  counts:
    - id
    - label
    - count
    - code_matches
  codematches:
    - id
    - label
    - code_matches
  cnvFrequencies:
    - id
    - label
    - frequencymaps
  codes:
    - id
    - label
  ids:
    - id

