collection_name: collations
defaults:
  method: counts
  response_entity_id: collation
integer_keys:
  - count
  - code_matches
method_keys:
  details: []
  child_terms:
    - id
    - label
    - count
    - child_terms
    - code_matches
    - collation_type
    - type
    - reference
  paths:
    - id
    - label
    - count
    - code_matches
    - child_terms
    - hierarchy_paths
    - collation_type
    - type
    - reference
  counts:
    - id
    - label
    - count
    - code_matches
    - collation_type
    - type
    - reference
  codematches:
    - id
    - label
    - code_matches
    - collation_type
    - type
    - reference
  ids:
    - id
    - label
