bycon_definition_files:
  - filter_definitions
  - dataset_definitions
collection_name: collations
defaults:
  dataset_ids:
    - progenetix
  method: counts
  filters:
    - NCIT
    - icdom
    - icdot
    - cellosaurus
meta:
  response_type: collations
  returned_schemas:
    - entity_type: collation
      schema: https://progenetix.org/services/schemas/Collation/
  info: >
    The main collations payload can be accessed in `results`.
integer_keys:
  - count
  - code_matches
methods:
  child_terms:
    - id
    - label
    - count
    - child_terms
    - code_matches
    - collation_type
    - type
  paths:
    - id
    - label
    - count
    - code_matches
    - child_terms
    - hierarchy_paths
    - collation_type
    - type
  counts:
    - id
    - label
    - count
    - code_matches
    - collation_type
    - type
  codematches:
    - id
    - label
    - code_matches
    - collation_type
    - type
  codes:
    - id
    - label
  ids:
    - id
