io_params:
  id:
    db_key: id
    type: string
  description:
    db_key: description
    type: string
  tnm:
    db_key: info.tnm
    type: string
  stage:
    db_key: info.stage
    type: string
  grade:
    db_key: info.grade
    type: string
  age_iso:
    db_key: age_at_collection.age
    type: string
  death:
    db_key: info.death
    type: string
  followup_months:
    db_key: info.followup_months
    type: string
  geoprov_city:
    db_key: provenance.geo.city
    type: string
  geoprov_country:
    db_key: provenance.geo.country
    type: string
  geoprov_iso_alpha3:
    db_key: provenance.geo.ISO-3166-alpha3
    type: string
  geoprov_lat:
    db_key: provenance.geo.latitude
    type: float
  geoprov_long:
    db_key: provenance.geo.longitude
    type: float
  cnv_fraction:
    db_key: info.cnvstatistics.cnvfraction
    type: float
  cnv_del_fraction:
    db_key: info.cnvstatistics.delfraction
    type: float
  cnv_dup_fraction:
    db_key: info.cnvstatistics.dupfraction
    type: float
io_prefixes:
  - icdom
  - icdot
  - NCIT
  - UBERON
  - MONDO
  - PMID
  - EFO
  - geo:GSM
  - geo:GSE
  - geo:GPL
  - cellosaurus
  - arrayexpress
