defaults:
  method: counts
  response_type: return_dbstats
  stats_number: 1
meta:
  response_type: dbstats
  returned_schemas:
    - https://progenetix.org/services/schemas/DBstats/
  info: >
    The latest dbstats payload can be accessed in `response.results[0]`.
methods:
  counts:
    - counts
  filtering_terms:
    - counts
    - filtering_terms
