bycon_definition_files:
  - service_mappings
  - dataset_definitions
  - filter_definitions
defaults:
  dataset_ids:
    - progenetix
  method: counts
  response_type: dbstats
  stats_number: 1
meta:
  returned_schemas:
    - entity_type: dbstats
      schema: https://progenetix.org/services/schemas/DBstats/
  info: >
    The latest dbstats payload can be accessed in `response.results`.
method_keys:
  counts:
    - counts
  filtering_terms:
    - counts
    - filtering_terms
