bycon_definition_files:
  - config
  - dataset_definitions
  - filter_definitions
  - geoloc_definitions
  - variant_definitions
  - handover_definitions
meta:
  response_type: deliveries
  info: >
    Deliveries can be in any of the core data schemas.
query_keys:
  - _id
  - id
  - accessid
