defaults:
  dataset_ids:
    - progenetix
  coll: genespans
  assembly_id: GRCh38
  query_fields:
    - gene_symbol
    - gene_entrez_id
  query_precision: "exact"
  db: progenetix
  coll: genespans
meta:
  response_type: genespans
  returned_schemas:
    GeneSpan: https://progenetix.org/services/schemas/GeneSpan/
  info: >
    The main genes payload can be accessed in `response.results`.
assembly_ids:
  - GRCh38
