defaults:
  dataset_ids:
    - progenetix
  assembly_id: GRCh38
  query_fields:
    - symbol
    - ensembl_gene_ids
    - synonyms
  db: progenetix
  coll: genes
meta:
  response_type: genespans
  returned_schemas:
    ProgenetixGene: https://progenetix.org/services/schemas/ProgenetixGene/
  info: >
    The main genes payload can be accessed in `results`.
assembly_ids:
  - GRCh38
