defaults:
  db: progenetix
  coll: genespans
  assembly_id: GRCh38
  query_fields:
    - gene_symbol
meta:
  response_type: genespans
  returned_schemas:
    GeneSpan: https://progenetix.org/services/schemas/GeneSpan/
  info: >
    The main genes payload can be accessed in `response.results`.
assembly_ids:
  - GRCh38
