defaults:
  dataset_ids:
    - progenetix
  geo_db: progenetix
  geo_coll: geolocs
  request_type: city
bycon_definition_files:
  - config
  - geoloc_definitions
meta:
  response_type: geolocs
  returned_schemas:
    GeoLocation: https://progenetix.org/services/schemas/GeoLocation/
  info: >
    The main geolocs payload can be accessed in `results`.
geo_root: 'provenance.geo'
