bycon_definition_files:
  - geoloc_definitions
  - services_mappings
  - beacon_mappings
defaults:
  dataset_ids:
    - progenetix
  geo_db: progenetix
  geo_coll: geolocs
  request_type: city
meta:
  response_entity_id: geolocs
  returned_schemas:
    - entity_type: genespan
      schema: https://progenetix.org/services/schemas/GeoLocation/
  info: >
    The main geolocs payload can be accessed in `response.results`.
geo_root: 'provenance.geo'
