format_patterns:

# local patterns

  - pattern: '^(pgx\:)?((pgxbs)(\-)([\w\-\.]{4,128}))$'
    link: '/biosamples/details?datasetIds=progenetix&id='

  - pattern: '^(pgx\:)?((pgxcs)(\-)([\w\-\.]{4,128}))$'
    link: '/callsets/details?datasetIds=progenetix&id='

  - pattern: '^(pgx\:)?((pgxind)(\-)([\w\-\.]{4,128}))$'
    link: '/individuals/details?datasetIds=progenetix&id='

  - pattern: '^(pgx\:)?((icdom)(\-)([\d]{5})?)$'
    link: '/subsets/list?datasetIds=progenetix&filters='

  - pattern: '^(pgx\:)?((icdot)(\-)(C\d\d?\.\d)?)$'
    link: '/subsets/list?datasetIds=progenetix&filters='

  - pattern: '^(pgx\:)?((NCIT)([:_])(C[\d]{4,8})?)$'
    link: '/subsets/list?datasetIds=progenetix&filters='

# public prefix patterns (with possible underscore replacement)

  - pattern: '^(pgx\:)?((PMID)([:_])([\d]{5,10})?)$'
    link: '/publications/details?id='

  - pattern: '^(pgx\:)?((cellosaurus)([:_])(CVCL_[A-Z0-9]{4})?)$'
    examples:
      - cellosaurus:CVCL_0022
      - pgx:cellosaurus_CVCL_0022
    link: '/biosamples/by-curie/'

  - pattern: '^(pgx\:)?(geo)(([:_])(G(PL|SM|SE|DS)\d+))$'
    examples:
      - cellosaurus:CVCL_0022
      - pgx:cellosaurus_CVCL_0022
    link: '/biosamples/by-curie/'
