format_patterns:

# local patterns
# TODO: adjust the internal ids w/ prefix

  - pattern: '^(?:pgx:)?(pgxbs-[\w\-\.]{4,128})$'
    link: '/biosamples/details?datasetIds=progenetix&id='
    prepend_if_missing: ""

  - pattern: '^(?:pgx:)?(pgxcs-[\w\-\.]{4,128})$'
    link: '/callsets/details?datasetIds=progenetix&id='
    prepend_if_missing: ""

  - pattern: '^(?:pgx:)?(pgxind-[\w\-\.]{4,128})$'
    link: '/individuals/details?datasetIds=progenetix&id='
    prepend_if_missing: ""

  - pattern: '^(?:pgx:)?(icdom-[\d]{1,5}(?:-\d{1,5})?)$'
    link: '/subsets/subsetdetails/?datasetIds=progenetix&id='
    prepend_if_missing: "pgx:"

  - pattern: '^(?:pgx:)?(icdot-C\d\d?(?:\.\d)?)$'
    link: '/subsets/subsetdetails/?datasetIds=progenetix&id='
    prepend_if_missing: "pgx:"

  - pattern: '^(?:pgx:)?(cohort-\w+)$'
    examples:
      - pgxcohort-TCGAcancers
    link: '/subsets/cohorts/?datasetIds=progenetix&filters='
    prepend_if_missing: "pgx:"

# public prefix patterns (with possible underscore replacement)

  - pattern: '^(?:pgx:)?(NCIT:C\d{4,8})$'
    link: '/subsets/subsetdetails/?datasetIds=progenetix&id='

  - pattern: '^(?:pgx:)?(PMID:\d{5,10})$'
    link: '/publications/details?id='

  - pattern: '^(?:pgx:)?(cellosaurus:CVCL_[A-Z0-9]{4})$'
    examples:
      - cellosaurus:CVCL_0022
      - pgx:cellosaurus:CVCL_0022
    link: '/subsets/subsetdetails/?datasetIds=progenetix&id='

  - pattern: '^(?:pgx:)?(cbioportal:\w[\w\-]+?\w)$'
    examples:
      - cbioportal:prad_p1000
    link: '/subsets/subsetdetails/?datasetIds=progenetix&id='

  - pattern: '^(?:pgx:)?(geo:G(?:PL|SE|DS)\d+)$'
    examples:
      - geo:GPL6801
    link: '/subsets/subsetdetails/?datasetIds=progenetix&id='

  - pattern: '^(?:pgx:)?(geo:GSM\d+)$'
    examples:
      - geo:GSM491153
    link: '/biosamples/details?datasetIds=progenetix&id='

