bycon_definition_files:
  - filter_definitions
  - variant_definitions
  - dataset_definitions
  - interval_definitions
  - services_mappings
defaults:
  dataset_ids:
    - progenetix
  method: frequencies
  genome_binning: 1Mb
  response_entity_id: interval_frequencies
meta:
  info: >
    The main collations payload can be accessed in `response.results`.
integer_keys:
  - count
  - code_matches
