bycon_definition_files:
  - config
  - filter_definitions
  - variant_definitions
  - dataset_definitions
  - interval_definitions
frequency_collection_name: frequencymaps
defaults:
  dataset_ids:
    - progenetix
  method: frequencies
  genome_binning: 1Mb
meta:
  response_type: interval_frequencies
  returned_schemas:
    Collation: TBD
  info: >
    The main collations payload can be accessed in `response.results`.
methods:
  frequencies:
    - interval_frequencies
    - id
    - label
  pgxseg:
    - interval_frequencies
    - id
    - label
integer_keys:
  - count
  - code_matches
collationed:
  geo:
    pattern: '^(geo)[:]((GSE)|(GPL))'
    is_series: True
    child_pattern: '^(geo)[:]GSM'
  NCIT:
    pattern: '^(NCIT)[:]C'
    is_series: False
  icdom:
    pattern: '^(icdom)[\-]\d'
    is_series: False
  icdot:
    pattern: '^(icdot)[\-]C'
    is_series: False
  cellosaurus:
    pattern: '^(cellosaurus)[:]CVCL'
    is_series: False
  PMID:
    pattern: '^(PMID)[:]\d'
    is_series: False
  UBERON:
    pattern: '^(UBERON)[:]\d'
    is_series: False
  cBP:
    pattern: '^(cBP)[\-]\w'
    is_series: False
  TCGA:
    pattern: '^(TCGA)[\-][\w\-]{2,20}$'
    is_series: True
    child_pattern: '^(TCGA)[\-]\w+?\-[\w\-]{15,30}$'
  pgxcohort:
    pattern: '^(pgxcohort)[\-]\w+?$'
    is_series: False
