bycon_definition_files:
  - filter_definitions
  - variant_definitions
  - dataset_definitions
  - interval_definitions
defaults:
  dataset_ids:
    - progenetix
  method: frequencies
  genome_binning: 1Mb
meta:
  response_type: interval_frequencies
  returned_schemas:
    Collation: TBD
  info: >
    The main collations payload can be accessed in `response.results`.
methods:
  frequencies: [ ]
  codematches: [ ]
integer_keys:
  - count
  - code_matches
