defaults:
  query_field: "code_group.id"
meta:
  response_type: ontologymaps
  returned_schemas:
    - https://progenetix.org/services/schemas/OntologyTermGroup/
    - https://progenetix.org/services/schemas/OntologyTerm/
  info: >
    The main code groups payload can be accessed in `response.results[0].term_groups`. All ontology terms are
    provided in `response.results[0].unique_terms`.

