service_names:
  empty_value: info
  cytomapper: cytomapper
  dbstats: dbstats
  deliveries: deliveries
  genespans: genespans
  genes: genespans
  geolocations: geolocations
  ids: ids
  interval_frequencies: intervalFrequencies
  intervalFrequencies: intervalFrequencies
  ontologymaps: ontologymaps
  publications: publications
  collations: collations
  schemas: schemas
rewrites:
  collationPlots: '/cgi/PGX/cgi/collationPlots.cgi'
  samplePlots: '/cgi/PGX/cgi/samplePlots.cgi'
  uploader: '/cgi/PGX/cgi/uploader.cgi'
  biosamples: '/beacon/biosamples/'
  variants: '/beacon/variants/'
  individuals: '/beacon/individuals/'
  phenopackets: '/beacon/individuals/'
