service_names:
  - beacon
  - biosamples
  - cytomapper
  - dbstats
  - deliveries
  - genespans
  - geolocations
  - ids
  - ontologymaps
  - publications
  - phenopackets
  - collations
  - schemas
  - variants
