service_names:
  root_path: info
  cytomapper: cytomapper
  dbstats: dbstats
  deliveries: deliveries
  genespans: genespans
  geolocations: geolocations
  ids: ids
  ontologymaps: ontologymaps
  publications: publications
  phenopackets: phenopackets
  collations: collations
  schemas: schemas
