defaults:
  dataset_ids:
    - progenetix
  method: details
  response_type: return_variants
meta:
  response_type: return_variants
  returned_schemas:
    Variant: https://progenetix.org/services/schemas/Variant/
  info: >
    The main variants payload can be accessed in `response.results`.
bycon_definition_files:
  - config
  - dataset_definitions
  - filter_definitions
  - geoloc_definitions
  - variant_definitions
  - handover_definitions
methods:
  digests:
    - digest
  compact:
    - _id
    - biosample_id
    - reference_name
    - start
    - end
    - variant_type
    - reference_bases
    - alternate_bases
  details:
    - _id
    - biosample_id
    - callset_id
    - digest
    - reference_name
    - start
    - end
    - variant_type
    - reference_bases
    - alternate_bases
    - info
