defaults:
  dataset_ids:
    - progenetix
  method: details
  response_type: return_variants
bycon_definition_files:
  - config
  - dataset_definitions
  - filter_definitions
  - geoloc_definitions
  - variant_definitions
  - handover_definitions
methods:
  digests:
    - digest
  details:
    - _id
    - biosample_id
    - callset_id
    - digest
    - reference_name
    - start
    - end
    - variant_type
    - reference_bases
    - alternate_bases
    - info
